huaweicloud/Sermant

README.md

【issue号】#19
【修改原因】
框架readme中插件开发流程不够明确
【修改内容】
readme中插件开发的内容
【检查者】@fuziye01
【用例描述】暂无用例
【自测情况】readme修改无需测试
【影响范围】不影响框架功能

修改readme中插件开发流程

---

README.md
javamesh-samples/javamesh-example/demo-application/pom.xml
javamesh-samples/javamesh-example/demo-application/src/main/java/com/huawei/example/demo/DemoApplication.java
javamesh-samples/javamesh-example/demo-plugin/pom.xml
javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/BootInstrumentation.java
javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/BootInterceptor.java
javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/DemoConfig.java
javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/demoService.java
javamesh-samples/javamesh-example/demo-plugin/src/main/resources/META-INF/services/com.huawei.apm.bootstrap.boot.PluginService
javamesh-samples/javamesh-example/demo-plugin/src/main/resources/META-INF/services/com.huawei.apm.bootstrap.config.BaseConfig
javamesh-samples/javamesh-example/demo-plugin/src/main/resources/META-INF/services/com.huawei.apm.bootstrap.definition.EnhanceDefinition
javamesh-samples/javamesh-example/pom.xml
javamesh-samples/pom.xml
pom.xml

【issue号】#22
【修改原因】1.readme文件中超链接失效；2.主要打包流程中不涉及清理和打产品包；3.打包过程中工程的上级目录会出现错误的文件
【修改内容】修正readme文件内容，细微调整打包过程中涉及的模块，重命名示例模块的包名，修复plugins模块中错误的shade插件使用
【检查者】@beetle-man @fuziye01 @3838438abcd @xzccfzy
【用例描述】暂无用例
【自测情况】本地功能测试通过
【影响范围】插件端现在需要显式指定shade插件 @beetle-man @3838438abcd @xzccfzy

【bug修复】修正readme文件内容，细微调整打包过程中涉及的模块，重命名示例模块的包名，修复plugins模块中错误的shade插件使用

---

javamesh-backend/src/main/java/com/huawei/apm/backend/common/conf/KafkaConf.java
javamesh-backend/src/main/java/com/huawei/apm/backend/server/ServerHandler.java
javamesh-backend/src/main/proto/Message.proto
javamesh-backend/src/main/resources/application.properties
javamesh-samples/javamesh-server-monitor/metric-server/pom.xml
javamesh-samples/javamesh-server-monitor/pom.xml
javamesh-samples/javamesh-server-monitor/protocol/pom.xml
javamesh-samples/javamesh-server-monitor/protocol/src/main/proto/IbmJvmMonitor.proto
javamesh-samples/javamesh-server-monitor/protocol/src/main/proto/ServerMonitor.proto
javamesh-samples/javamesh-server-monitor/server-monitor-plugin/pom.xml
javamesh-samples/javamesh-server-monitor/server-monitor-plugin/src/main/java/com/huawei/javamesh/sample/servermonitor/collector/IbmJvmMetricCollector.java
javamesh-samples/javamesh-server-monitor/server-monitor-plugin/src/main/java/com/huawei/javamesh/sample/servermonitor/service/IbmJvmCollectService.java
javamesh-samples/javamesh-server-monitor/server-monitor-plugin/src/main/java/com/huawei/javamesh/sample/servermonitor/service/ServerMonitorService.java
javamesh-samples/javamesh-server-monitor/server-monitor-plugin/src/main/resources/META-INF/services/com.huawei.apm.bootstrap.boot.PluginService

【issue号】#15 服务监控和JVM监控开发
【内容】
1.分离server资源采集和ibm jvm指标采集（解耦以适配新后台开发）
2.独立出protobuf协议模块（后台、插件共同依赖）

分离server资源采集和IBM jvm指标采集

---

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/integration/transport/netty/client/NettyClient.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/integration/transport/netty/client/Sender.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/integration/transport/netty/client/ThreadPools.java

【issue号】#84
【修改原因】
agent挂载宿主应用CPU占用率过高，修改统一消息发送模块netty客户端消息发送方式解决此问题。
【修改内容】
原代码已解决该问题，更新迁移代码，修改客户端消息发送方式。
【检查者】@fuziye01 @xuezechao-hub 
【用例描述】原有用例无需修改
【自测情况】1. 挂载agent在宿主应用，kafka中接收到netty发送过来的心跳数据；2. 本地自验CPU占用率显著下降
【影响范围】统一消息发送模块

【BUG】解决CPU占用率过高问题

---

javamesh-samples/javamesh-route/route-server/pom.xml

【issue号】#95
【修改内容】
增加route-server输出目录
【检查者】@beetle-man @fuziye01 @xuezechao-hub @HapThorin
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】javamesh-route后台输出目录

【bug】增加route-server输出目录

---

javamesh-samples/javamesh-flowrecord/flowrecord-replay/install_script/es-install.sh
javamesh-samples/javamesh-flowrecord/flowrecord-replay/install_script/kafka-install.sh
javamesh-samples/javamesh-flowrecord/flowrecord-replay/install_script/redis-install.sh
javamesh-samples/javamesh-flowrecord/flowrecord-replay/install_script/zookeeper-install.sh

【issue号】#99
【修改原因】
支持中间件快速部署
【修改内容】
新增中间件集群快速部署脚本
【检查者】@fuziye01 @xuezechao-hub @useless223 
【用例描述】暂无
【自测情况】本地自验通过
【影响范围】流量录制回放server

【chore】新增流量录制中间件快速部署脚本

---

javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/lubanops/log/CollectorLogFactory.java

【issue号】#101
【修改原因】
1. 日志信息没有同步打印到控制台
【修改内容】
1. premain中log添加consoleHandle
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】
1. 框架错误日志会打印在控制台

log同步输出到控制台

---

javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/lubanops/log/CollectorLogFactory.java

Reverts huaweicloud/java-mesh#102

Revert "log同步输出到控制台"

---

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/Config.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/DynamicConfigurationFactoryServiceImpl.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/nop/NopDynamicConfigurationService.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/service/DynamicConfigurationService.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/zookeeper/ZookeeperDynamicConfigurationService.java
javamesh-agentcore/javamesh-agentcore-core/src/main/resources/config/config.properties
javamesh-agentcore/javamesh-agentcore-core/src/test/java/com/huawei/apm/core/service/dynamicconfig/DynamicConfigurationFactoryServiceImplTest.java

Refractor some minus format.
Add interface for get configs from group and config.

Add config and group listener.

---

docs/README.md
docs/dev-guide/dev_plugin.md
docs/dev-guide/dev_sample.md
docs/dev-guide/service_dynamicconfig.md
docs/dev-guide/service_heartbeat.md
docs/dev-guide/service_send.md
docs/dev-guide/service_template.md
docs/user-guide/agentcore.md
docs/user-guide/backend.md
docs/user-guide/entrance.md
docs/user-guide/flowcontrol/document.md
docs/user-guide/flowrecord/document.md
docs/user-guide/hercules/document.md
docs/user-guide/online-stresstest/document.md
docs/user-guide/route/document.md
docs/user-guide/server-monitor/document.md
docs/user-guide/template/document.md
docs/user-guide/threadlocal/document.md
javamesh-backend/README.md
javamesh-samples/javamesh-flowcontrol/README.md
javamesh-samples/javamesh-flowrecord/README.md
javamesh-samples/javamesh-hercules/README.md
javamesh-samples/javamesh-route/README.md
javamesh-samples/javamesh-server-monitor/README.md
javamesh-samples/javamesh-threadlocal/README.md

【需求单号】#123
【修改原因】README文件需要定一个目录规范
【修改内容】编写新的README内容，为将来的README文件定一个目录规范
【检查者】@yangyshdan @fuziye01 @3838438abcd @xuezechao-hub @beetle-man @hujialiang4185 @zhongleijd @ssyyzs @pengyuyii
【用例描述】不涉及
【自测情况】不涉及
【影响范围】所有插件开发者 @3838438abcd @xuezechao-hub @beetle-man @hujialiang4185 @zhongleijd @ssyyzs @pengyuyii

【新功能】README目录规范

---

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/kie/KieDynamicConfigurationServiceImpl.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/kie/listener/SubscriberManager.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/utils/LabelGroupUtils.java
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/service/dynamicconfig/zookeeper/ZookeeperDynamicConfigurationService.java
javamesh-agentcore/javamesh-agentcore-core/src/test/java/com/huawei/apm/core/service/dynamicconfig/KieDynamicConfigurationServiceImplTest.java
javamesh-agentcore/javamesh-agentcore-core/src/test/java/com/huawei/apm/core/service/dynamicconfig/kie/LabelGroupUtilsTest.java
javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/RuleSyncer.java
javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/datasource/CseDataSourceManager.java
javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/config/FlowControlConfig.java
javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/datasource/DefaultDataSource.java
javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/datasource/DefaultDataSourceManager.java
javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/util/DataSourceInitUtils.java
javamesh-samples/javamesh-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/service/ConfigServiceImpl.java

【issue号/需求单号】#149
【修改原因】评审意见修改
【修改内容】
1. 标签组工具类挪到外层
2. 插件适配配置中心逻辑去除KIE相关内容
【检查者】@fuziye01 @HapThorin  @xuezechao-hub @beetle-man
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】配置中心与流控

【bug】修改评审意见

---

.github/workflows/maven.yml

【issue号/问题单号/需求单号】#152
【修改原因】原因一：提交pr之后，没有展示门禁结果
【修改内容】门禁配置文件修改了门禁触发条件
【检查者】@fuziye01 @HapThorin 
【用例描述】门禁配置修改不需要测试用例
【自测情况】无法自测，提交pr后显示门禁结果则修改生效
【影响范围】1. 对框架使用无影响  2. 开发者在提交pr后可以直接看到门禁结果

门禁配置修改，提交pr后显示门禁结果

---

README.md

What type of PR is this?
documentation
What this PR does / why we need it:
update related projects.
Which issue(s) this PR fixes:
#164 
Special notes for your reviewer:  @HapThorin 
Use case description:  readme update.
Does this PR introduce a user-facing change?
No
Additional documentation e.g., usage docs, etc.:
No

update readme.md by adding related projects.

---

javamesh-backend/.gitignore
javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/pom.xml
javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/dubbo/AliDubboInterceptor.java
javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/dubbo/DubboInterceptor.java
javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/PluginConfigUtil.java
javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/StringUtil.java

Reverts huaweicloud/java-mesh#181

Revert "删除skywalking依赖，添加asf copyright"

---

docs/user-guide/route/document.md
javamesh-plugins/javamesh-route/README.md
javamesh-plugins/javamesh-route/config/config.yaml

【issue号】 #177 
【修改原因】增加灰度发布文档
【修改内容】增加灰度发布文档
【检查者】@fuziye01 @HapThorin @xuezechao-hub @beetle-man
【用例描述】不涉及
【自测情况】本地自测通过
【影响范围】无

【文档】灰度发布文档添加

---

.github/pull_request_template.md

【issue号/问题单号/需求单号】#196
【修改内容】删除了pr模板中的检视人和修改原因
【用例描述】无需测试用例
【自测情况】本地检查通过
【影响范围】提交pr无需填写reviewer人和修改原因

Delete reviewer and reason in pr template

---

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/config/ConfigManager.java

【需求单号】#224
【修改内容】统一配置管理中，配置重复加载的日志整理，只有配置类的类型不一致时，才认为是重复加载
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】统一配置系统

【log】处理统一配置系统配置类重复加载误提示

---

docs/README.md
docs/dev-guide/third_party_copyright.md

【需求单号】#222
【修改内容】添加第三方版权说明手册
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】文档

【doc】添加第三方版权说明手册

---

LICENSE
docs/user-guide/flowcontrol/flowcontrol.md
docs/user-guide/flowcontrol/kie-configuration-document.md
docs/user-guide/flowcontrol/zk-configuration-document.md
javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/dynamicconfig/kie/listener/SubscriberManager.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DubboInterceptor.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/datasource/CseDataSourceManager.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/match/MatchManager.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/resolver/AbstractResolver.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/resolver/BulkheadRuleResolver.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/resolver/CircuitBreakerRuleResolver.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/resolver/RateLimitingRuleResolver.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/resolver/RetryResolver.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/BulkheadRule.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadException.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadRule.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadRuleManager.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadSlot.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/config/FlowControlConfig.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/datasource/kie/rule/RuleCenter.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/datasource/kie/rule/isolate/IsolateThreadRuleWrapper.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/entry/EntryFacade.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/FlowControlServiceImpl.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/util/SentinelRuleUtil.java
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/resources/META-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/main/resources/META-INF/services/com.huawei.flowcontrol.adapte.cse.resolver.AbstractResolver
javamesh-plugins/javamesh-flowcontrol/flowcontrol-plugin/src/test/java/com/huawei/flowcontrol/adapte/cse/test/RuleResolveTest.java

【issue号/问题单号/需求单号】#219
【修改内容】
- 完成流控隔离仓功能开发
- 修复dubbo场景消费者版本问题
- 优化流控返回机制
- 补充流控隔离仓文档
【检查者】@fuziye01 @HapThorin @xuezechao1  @beetle-man 
【用例描述】无
【自测情况】本地测试通过
【影响范围】流控功能

【feature/fix】流控隔离仓能力

---

README.md

【需求单号】#236
【修改内容】修正英文readme文档中存在中文字符的问题和windows运行demo命令错误的问题
【用例描述】不涉及
【自测情况】不涉及
【影响范围】readme文档

【doc】修正英文readme文档中存在中文字符的问题和windows运行demo命令错误的问题

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZookeeperDynamicConfigurationService.java

【issue号】 #234 
【修改原因】在首次添加监听器时，会有将监听路径节点的数据通知给监听器的逻辑，而这里存在一个问题，当监听节点不存在时，会抛出节点不存在的异常
【修改内容】修改ZK配置中心添加监听器逻辑，在通知前，判断监听路径的是否存在，仅当节点存在时才去通知监听器
【检查者】@fuziye01 @HapThorin  @beetle-man @xuezechao1 @provenceee
【用例描述】无
【自测情况】本地自测通过
【影响范围】使用配置中心的所有模块: 灰度调用@provenceee

【fix】修复zk节点不存在的问题

---

docs/dev-guide/service_send.md

【issue号/问题单号/需求单号】#252
【修改内容】docs/dev-guide/service_send.md添加内容
【用例描述】不涉及
【自测情况】不涉及
【影响范围】无

统一发送服务readme

---

sermant-package/resources/third-party-license.ftl

【问题单号】#220
【修改内容】修正third-party-license.ftl的header
【用例描述】不涉及
【自测情况】不涉及
【影响范围】third-party-license.ftl文件

【doc】修正third-party-license.ftl的header

---

.github/workflows/maven.yml
docs/dev-guide/dev_plugin_module.md
docs/user-guide/agentcore.md
docs/user-guide/flowcontrol/flowcontrol.md
docs/user-guide/flowcontrol/kie-configuration-document.md
docs/user-guide/flowcontrol/zk-configuration-document.md
docs/user-guide/route/document.md
pom.xml
sermant-agentcore/sermant-agentcore-core/pom.xml
sermant-package/pom.xml
sermant-plugins/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-replay/flowre-console/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-replay/flowrecord-console/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-replay/flowreplay/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-replay/mockserver/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-replay/pom.xml

【问题单号】#258
【修改内容】规范版本，暂统一为1.0.0，以后可通过mvn versions:set命令统一修改版本号
【用例描述】不涉及
【自测情况】本地测试通过
【影响范围】项目版本号

【perf】规范版本，暂统一为1.0.0，以后可通过mvn versions:set命令统一修改版本号

---

docs/dev-guide/dev_plugin_code.md
docs/dev-guide/service_dynamicconfig.md
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperBufferedClient.java

【需求单号】#267
【修改内容】补充动态配置服务的开发手册
【用例描述】不涉及
【自测情况】不涉及
【影响范围】动态配置服务的开发手册

【Doc】补充动态配置服务的开发手册

---

.github/workflows/stale.yml

【问题单号】#269
【修改内容】暂时将关闭issue和pr的step合并，提升处理总条数
【用例描述】不涉及
【自测情况】不涉及
【影响范围】工作流

【workflow】暂时将关闭issue和pr的step合并，提升处理总条数

---

docs/README.md
docs/dev-guide/version_manage.md

【需求单号】#271
【修改内容】添加版本管理手册
【用例描述】不涉及
【自测情况】不涉及
【影响范围】版本管理

【Doc】添加版本管理手册

---

pom.xml

【需求单号】#274
【修改内容】更新log4j桥接包的版本
【用例描述】不涉及
【自测情况】不涉及
【影响范围】无

【perf】更新log4j桥接包的版本

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/template/BootstrapConstTemplate.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/template/BootstrapInstTemplate.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/agent/template/BootstrapStaticTemplate.java

【问题单号】#276
【修改内容】修复增强模板类的名称构建时对入参处理错误的问题
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】对启动类加载器加载的类做增强

【Fix】修复增强模板类的名称构建时对入参处理错误的问题

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/common/BootArgsIndexer.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/PluginManager.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/heartbeat/HeartbeatServiceImpl.java
sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/AgentPremain.java

【问题单号】#280
【修改内容】修复JarFile没有关的问题，同时整理一下插件管理器中的JarFile元数据校验方法逻辑
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】无

【Fix】修复JarFile没有关的问题

---

sermant-plugins/sermant-hercules/hercules-adaptation/src/main/java/com/huawei/hercules/controller/perftest/PerfTestController.java
sermant-plugins/sermant-hercules/hercules-adaptation/src/main/java/com/huawei/hercules/controller/scenario/ScenarioController.java
sermant-plugins/sermant-hercules/hercules-adaptation/src/main/java/com/huawei/hercules/controller/script/ScriptController.java
sermant-plugins/sermant-hercules/hercules-adaptation/src/main/java/com/huawei/hercules/controller/testreport/TestReportController.java
sermant-plugins/sermant-hercules/hercules-adaptation/src/main/java/com/huawei/hercules/util/MysqlCharUtil.java
sermant-plugins/sermant-hercules/hercules-server/.editorconfig
sermant-plugins/sermant-hercules/hercules-server/hercules-controller/src/main/java/com/huawei/argus/perftest/controller/PerfTestTaskController.java
sermant-plugins/sermant-hercules/hercules-server/hercules-controller/src/main/java/com/huawei/argus/perftest/util/PerfTestUtil.java

【issue号/问题单号/需求单号】#284
【修改内容】全链路压测中修复测试发现的缺陷，bug id: BUG2021121701540 BUG2021121600730 BUG2021121501470 BUG2021121401474 BUG2021121301009
【用例描述】测试环境问题回归
【自测情况】测试环境已经验收通过，测试已经关闭问题单

【hercules】修复全链路压测测试发现的缺陷

---

docs/dev-guide/third_party_copyright.md

Clean up the description of the README file about the third party license generation.

Update the readme file of the LICENSE generation

---

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/AbstractPluginService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/AlibabaDubboService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/ApacheDubboService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/DispatcherServletService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/KieConfigurationService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/ServiceCombServiceMetaService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/adapte/cse/rule/isolate/IsolateThreadSlot.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/service/AlibabaDubboServiceImpl.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/service/ApacheDubboServiceImpl.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/service/DispatcherServletServiceImpl.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/service/KieConfigurationServiceImpl.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/flowcontrol/service/ServiceCombServiceMetaServiceImpl.java

【issue号】#286
【修改内容】将`PluginService`实现下移到子类
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控模块，其他不影响

【Fix】PluginService实现下移

---

sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java
sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ScRegister.java
sermant-plugins/sermant-route/config/config.yaml
sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/ServiceInstanceListSupplierDefinition.java
sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/register/RegistrationDefinition.java
sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/RegistrationInterceptor.java
sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/ServiceInstanceListSupplierInterceptor.java
sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/ServiceInstanceListSupplierService.java
sermant-plugins/sermant-route/gray-feign-http-9.x-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.agent.definition.EnhanceDefinition
sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/ConfigServiceImpl.java
sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientServiceImpl.java
sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/RegisterServiceImpl.java
sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/ServiceInstanceListSupplierServiceImpl.java
sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.service.PluginService
sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/config/GrayConfig.java
sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/constants/GrayConstant.java

【issue号/问题单号/需求单号】#298
【修改内容】springcloud灰度发布对接CSE
【用例描述】后续补齐
【自测情况】自测通过
【影响范围】与注册插件拦截了同一个类方法，测试过先走灰度拦截，再走注册拦截，相互不影响

springcloud灰度发布对接CSE

---

pom.xml
sermant-agentcore/sermant-agentcore-core/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-replay/pom.xml

【问题单号】#318
【修改内容】更新netty、protobuf和logback的版本，避免低版本依赖的bug
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】netty、protobuf和logback的版本

【BUG】更新netty、protobuf和logback的版本，避免低版本依赖的bug

---

docs/README.md
docs/user-guide/feature-list.md

【需求单号】#320
【修改内容】更新插件功能列表文档
【用例描述】不涉及
【自测情况】本地测试通过
【影响范围】文档

【DOC】更新插件功能列表文档

---

.github/workflows/maven.yml
checkstyle.xml

【issue号/问题单号/需求单号】#308
【修改内容】流水线增加代码规范检查
【用例描述】不需用例，未修改代码
【自测情况】1、提交测试pr验证通过，静态检查配置生效
【影响范围】1、所有开发者提交的代码需要通过代码静态检查之后，才可以合入

门禁增加代码规范检查

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/template/MethodKeyCreator.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/utils/ClassLoaderUtils.java

【issue号/问题单号/需求单号】#333
【修改内容】类锁添加访问权限，拦截数组参数方法失效问题修改
【用例描述】暂不需测试用例
【自测情况】本地检查通过

【BUG】类锁添加访问权限，拦截数组参数失效问题修改

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/transformer/BootstrapTransformer.java

【issue号/问题单号/需求单号】#335
【修改内容】增加了拦截器全局集，修复启动类加载器加载的类被重复定义的问题
【用例描述】暂不需测试用例
【影响范围】1、用户开发插件时，启动类加载器加载的类不会被重复定义

【BUG】修复启动类加载器加载的类被重复定义

---

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
sermant-plugins/sermant-register-center/config/config.yaml
sermant-plugins/sermant-register-center/register-common/src/main/java/com/huawei/register/config/RegisterConfig.java

【issue号/问题单号/需求单号】#353
【修改内容】统一注册与流控服务信息获取途径；修复部分流控bug
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】流控与注册插件

【feature】流控与注册中心统一配置修改

---

sermant-plugins/sermant-flowrecord/config/config.yaml
sermant-plugins/sermant-flowrecord/flowrecord-plugin/pom.xml
sermant-plugins/sermant-flowrecord/flowrecord-service/pom.xml

【issue号/问题单号/需求单号】#351
【修改内容】录制插件增加配置文件，录制插件service模块pom文件添加scope属性
【用例描述】暂不需用例
【影响范围】1、对使用录制插件的用户可以通过修改配置文件避免重复打包

【BUG】录制插件添加config文件，录制插件service模块pom文件添加scope属性

---

sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/config/DemoConfig.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/kafka/IbmJvmMonitorKafkaReceiver.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/service/AgentRegistrationService.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/service/ServerMetricService.java
sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/plugin/monitor/common/utils/CommonUtil.java
sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/plugin/servermonitor/command/CommandExecutor.java
sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/plugin/servermonitor/command/MemoryCommand.java
sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/plugin/servermonitor/common/CheckIBMParameter.java

【issue】https://github.com/huaweicloud/Sermant/issues/341
【修改内容】
修改 sermant-example 和 sermant-server-monitor 中相关规范
【用例描述】不需要修改
【自测情况】修改规范无需修改用例
【影响范围】无
【遗留问题】sermant-server-monitor中protobuf编译生成的文件还是有一些问题，暂时不知道怎么修改

[fix] code style

---

sermant-plugins/sermant-flowcontrol/flowcontrol-server/pom.xml

【issue号/问题单号/需求单号】#342
【修改内容】升级流控插件部分依赖版本，规避CVE
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】仅影响本模块

【BUG】修复流控依赖漏洞

---

sermant-plugins/sermant-register-center/dubbo-register-plugin/src/main/java/com/huawei/dubbo/register/interceptor/RegistryProtocolInterceptor.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/main/java/com/huawei/dubbo/register/utils/ReflectUtils.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/ConfigValidationInterceptorTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/ExtensionLoaderInterceptorTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/MigrationRuleHandlerInterceptorTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/MigrationRuleInterceptorTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/ReflectUtilsTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/RegistryFactoryTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/RegistryProtocolInterceptorTest.java
sermant-plugins/sermant-register-center/dubbo-register-plugin/src/test/java/com/huawei/dubbo/register/TestConstant.java
sermant-plugins/sermant-register-center/dubbo-register-service/pom.xml
sermant-plugins/sermant-register-center/dubbo-register-service/src/main/java/com/huawei/dubbo/register/service/RegistryServiceImpl.java
sermant-plugins/sermant-register-center/dubbo-register-service/src/test/java/com/huawei/dubbo/register/ApplicationConfigServiceTest.java
sermant-plugins/sermant-register-center/dubbo-register-service/src/test/java/com/huawei/dubbo/register/RegistryConfigServiceTest.java

【issue号/问题单号/需求单号】 #345 
【修改内容】dubbo注册增加UT
【检查者】@fuziye01 @HapThorin @beetle-man @xuezechao1 @justforstudy-A
【用例描述】单元测试通过
【自测情况】本地测试通过
【影响范围】不影响插件

【feature】dubbo注册增加UT

---

sermant-plugins/sermant-register-center/config/config.yaml
sermant-plugins/sermant-route/gray-dubbo-2.7.x-plugin/src/main/java/com/huawei/gray/dubbo/definition/AbstractInstDefinition.java
sermant-plugins/sermant-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/service/RegistrationServiceImpl.java
sermant-plugins/sermant-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/strategy/type/ObjectTypeStrategy.java
sermant-plugins/sermant-route/gray-dubbo-2.7.x-service/src/main/java/com/huawei/gray/dubbo/utils/FieldPrivilegedAction.java
sermant-plugins/sermant-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/context/CurrentInstance.java
sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/Match.java
sermant-plugins/sermant-route/route-common/src/main/java/com/huawei/route/common/gray/label/entity/ValueMatchDeserializer.java

【issue号/问题单号/需求单号】 #341  #342 
【修改内容】修改代码规范与安全问题
【检查者】@fuziye01 @HapThorin @beetle-man @xuezechao1 @justforstudy-A
【用例描述】单元测试通过
【自测情况】本地测试通过
【影响范围】dubbo注册插件，灰度发布

[fix] 修改dubbo注册插件，灰度发布的代码规范与安全问题

---

sermant-plugins/sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoFieldSetInterceptor.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/controller/ConnectionPoolController.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/controller/IbmPoolController.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/controller/OpenJdkJvmController.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/controller/ServerMetricController.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/kafka/OpenJdkJvmMonitorKafkaReceiver.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/service/AgentRegistrationService.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/service/ConnectionPoolService.java
sermant-plugins/sermant-server-monitor/metric-server/src/main/java/com/huawei/sermant/metricserver/service/InfluxService.java
sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/plugin/monitor/common/collect/CollectTask.java
sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/plugin/monitor/common/utils/CommonUtil.java
sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/plugin/servermonitor/command/CommandExecutor.java
sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/plugin/servermonitor/service/MonitorService.java

【issue】https://github.com/huaweicloud/Sermant/issues/341
【修改内容】
修改 sermant-example 和 sermant-server-monitor 中相关规范
【用例描述】不需要修改
【自测情况】修改规范无需修改用例
【影响范围】无
【遗留问题】sermant-server-monitor中protobuf编译生成的文件还是有一些问题，暂时不知道怎么修改

[fix] sermant-example & sermant-server-monitor code check

---

docs/user-guide/register/document.md
docs/user-guide/register/dubbo-register-migiration.md

【issue号/问题单号/需求单号】 #345 
【修改内容】修改dubbo注册中心文档
【检查者】@fuziye01 @HapThorin @beetle-man @xuezechao1 @justforstudy-A
【用例描述】不涉及
【自测情况】不涉及
【影响范围】不影响插件

【DOC】修改dubbo注册中心文档

---

sermant-plugins/sermant-hercules/ngrinder/hercules-function/pom.xml
sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/config/HttpClientConfig.java
sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/service/HttpClientServiceInterface.java
sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/service/HttpDeleteWithBody.java
sermant-plugins/sermant-hercules/ngrinder/hercules-function/src/main/java/com/huawei/test/configelement/service/impl/HttpClientService.java

【issue号/问题单号/需求单号】#343
【修改内容】增加压测平台http sampler高级选项功能
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】对用户的使用没有影响

【feature】压测平台中http请求支持httpclient连接复用

---

docs/user-guide/register/spring-cloud-register-migiration.md
sermant-plugins/sermant-register-center/config/config.yaml
sermant-plugins/sermant-register-center/register-common/src/main/java/com/huawei/register/config/ConfigConstants.java
sermant-plugins/sermant-register-center/register-common/src/main/java/com/huawei/register/config/RegisterConfig.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/handler/SingleStateCloseHandler.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ClientConfigInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ClientConfigurationInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/DiscoveryClientInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/RegistrationInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ServerListInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ConsulHealthInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ConsulWatchInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/EurekaHealthInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/NacosHealthInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ZookeeperHealthInterceptor.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/support/InstanceInterceptorSupport.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/support/RegisterSwitchSupport.java

【issue号/问题单号/需求单号】#380
【修改内容】增加spring注册插件开关
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】仅对当前模块有影响

【fix】增加spring注册插件注册开关

---

sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/utils/HostUtils.java
sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java
sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/impl/RegisterCenterServiceImpl.java

【issue号/问题单号/需求单号】#396
【修改内容】
1、优化域名与IP获取
2、支持注册SC SSL
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】仅对当前模块影响

【feature】优化代码，增加Spring注册插件对SSL的支持

---

sermant-plugins/sermant-register-center/config/config.yaml
sermant-plugins/sermant-register-center/dubbo-register-service/src/main/java/com/huawei/dubbo/register/service/RegistryServiceImpl.java

【issue号/问题单号/需求单号】 #393 
【修改内容】dubbo注册插件增加对ssl的支持
【检查者】@fuziye01 @HapThorin @xuezechao1 @justforstudy-A
【用例描述】不涉及
【自测情况】本地测试通过
【影响范围】注册插件

【feature】dubbo注册插件增加对ssl的支持

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/utils/ConfigValueUtil.java

【issue号/问题单号/需求单号】#391
【修改内容】修改了获取${}配置验证逻辑
【用例描述】不需测试用例
【自测情况】本地检查通过
【影响范围】对用户使用无影响

【BUG】解析配置正则表达式bug修复

---

checkstyle.xml

【issue号/问题单号/需求单号】#401
【修改内容】完善了checkstyle规则文件
【用例描述】不需测试用例
【自测情况】本地静态检查通过

完善checkstyle

---

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/handler/RetryHandlerV2.java

【issue号/问题单号/需求单号】#403
【修改内容】修复流控重试次数
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控模块

【fix】修复流控多一次重试的问题

---

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/FlowControlConfig.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/test/java/com/huawei/flowcontrol/common/adapte/cse/match/OperatorTest.java
sermant-plugins/sermant-flowcontrol/flowcontrol-resilience4j-service/src/test/java/com/huawei/fowcontrol/res4j/util/Rest4jExceptionUtilsTest.java
sermant-plugins/sermant-register-center/register-common/src/main/java/com/huawei/register/config/ConfigConstants.java
sermant-plugins/sermant-register-center/register-common/src/main/java/com/huawei/register/config/RegisterConfig.java
sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/utils/HostUtils.java
sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java
sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ScRegister.java

【issue号/问题单号/需求单号】#397
【修改内容】
1、修正无法隔离app的bug
2、增加数据中心隔离相关逻辑
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】暂无

【fix】修复spring注册插件无法隔离app实例的问题

---

checkstyle.xml

【issue号/问题单号/需求单号】#401
【修改内容】修改了版权年份与since年份检查正则表达式
【用例描述】不需测试用例
【自测情况】本地静态检查通过

【bug】版权年份与since年份正则修改

---

sermant-backend/pom.xml

【issue号/问题单号/需求单号】#405
【修改内容】修改了backend依赖版本为没有漏洞的版本
【用例描述】不需测试用例
【自测情况】本地静态检查通过

backend依赖漏洞问题修复

---

sermant-plugins/pom.xml

【issue号/问题单号/需求单号】#409
【修改内容】默认编译选项插件部分只保留流控，注册插件
【用例描述】不需测试用例
【自测情况】本地静态检查通过

默认编译只保留流控,注册插件

---

checkstyle.xml

【issue号/问题单号/需求单号】#401
【修改内容】checkstyle添加可忽略检测注解配置
【用例描述】不需测试用例
【自测情况】本地静态检查通过

checkstyle添加可忽略检测注解配置

---

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/exception/InvokerException.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/exception/InvokerWrapperException.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/AlibabaDubboClusterInvoker.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/ApacheDubboClusterInvoker.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/handler/RetryHandlerV2.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/InterceptorSupporter.java
sermant-plugins/sermant-flowcontrol/flowcontrol-server/pom.xml
sermant-plugins/sermant-register-center/spring-cloud-register-service/pom.xml

【issue号/问题单号/需求单号】#414
【修改内容】
1、升级插件依赖，避免CVE
2、修改checkstyle，规范代码
【用例描述】暂无用例
【检查者】@fuziye01 @HapThorin @xuezechao1 @robotLJW @provenceee 
【自测情况】本地自测通过
【影响范围】流控与spring注册插件

【fix】修复流控与spring注册插件相关规范

---

pom.xml

【issue号/问题单号/需求单号】#417
【修改内容】修改了agentcore依赖版本为无漏洞版本
【用例描述】不需要更改用例
【自测情况】本地静态检查已过
【影响范围】对用户无使用影响

【fix】修复agentcore开源版本漏洞

---

sermant-backend/pom.xml
sermant-backend/src/main/java/com/huawei/sermant/backend/common/exception/KafkaTopicException.java
sermant-backend/src/main/java/com/huawei/sermant/backend/common/exception/ZookeeperDynamicConfigurationException.java
sermant-backend/src/main/java/com/huawei/sermant/backend/kafka/KafkaConsumerManager.java
sermant-backend/src/main/java/com/huawei/sermant/backend/kafka/KafkaProducerManager.java
sermant-backend/src/main/java/com/huawei/sermant/backend/server/HttpServer.java
sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/Config.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/DynamicConfigurationFactoryServiceImpl.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/kie/client/ClientUrlManager.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/kie/listener/SubscriberManager.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/service/ConfigChangedEvent.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/service/DynamicConfigType.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/service/DynamicConfigurationService.java
sermant-backend/src/main/java/com/huawei/sermant/backend/service/dynamicconfig/zookeeper/ZookeeperDynamicConfigurationService.java
sermant-backend/src/main/java/com/huawei/sermant/backend/util/DateUtil.java

【issue号/问题单号/需求单号】#399
【修改内容】修改了backend代码规范，三方组件依赖版本
【用例描述】不需测试用例
【自测情况】本地静态检查通过

backend编码规范，安全问题整改

---

docs/user-guide/register/document.md
docs/user-guide/register/dubbo-register-migiration.md
sermant-plugins/sermant-register-center/config/config.yaml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-common/pom.xml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-common/src/main/java/com/huawei/dubbotest/service/TestInterface.java
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-consumer/pom.xml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-consumer/src/main/java/com/huawei/dubbotest/ConsumerApplication.java
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-consumer/src/main/java/com/huawei/dubbotest/controller/DubboController.java
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-consumer/src/main/resources/application.yaml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-consumer/src/main/resources/dubbo/consumer.xml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-provider/pom.xml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-provider/src/main/java/com/huawei/dubbotest/ProviderApplication.java
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-provider/src/main/java/com/huawei/dubbotest/impl/TestInterfaceImpl.java
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-provider/src/main/resources/application.yaml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/dubbo-provider/src/main/resources/dubbo/provider.xml
sermant-plugins/sermant-register-center/demo-register/demo-register-dubbo/pom.xml
sermant-plugins/sermant-register-center/demo-register/pom.xml
sermant-plugins/sermant-register-center/pom.xml

【issue号/问题单号/需求单号】 #423 
【修改内容】完善dubbo注册插件文档与demo
【检查者】@fuziye01 @HapThorin @xuezechao1 @justforstudy-A
【用例描述】不涉及
【自测情况】不涉及
【影响范围】dubbo注册插件文档

【feature】完善dubbo注册插件文档与demo

---

docs/user-guide/flowcontrol/flowcontrol.md
docs/user-guide/flowcontrol/kie-configuration-document.md
docs/user-guide/flowcontrol/zk-configuration-document.md
docs/user-guide/register/document.md
sermant-agentcore/sermant-agentcore-core/config/config.properties
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/strategy/LoadYamlStrategy.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/utils/ConfigValueUtil.java
sermant-plugins/sermant-flowcontrol/config/config.yaml

【issue号/问题单号/需求单号】#430
【修改内容】
1、增加配置文件默认环境变量支持
2、修正流控与注册插件配置
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】所有使用到统一配置的模块

【fix】修复环境变量问题

---

sermant-backend/pom.xml

【issue号/问题单号/需求单号】#405
【修改内容】更改tomcat版本为9.0.43
【用例描述】不需测试用例
【自测情况】本地静态检查通过

更改tomcat版本为9.0.43

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/config/DynamicConfig.java

【issue号/问题单号/需求单号】#430
【修改内容】配置文件中配置中心类忽略大小写
【用例描述】不需测试用例
【自测情况】本地静态检查通过

配置文件支持忽略配置中心大小写

---

checkstyle.xml

【issue号/问题单号/需求单号】#440
【修改内容】删除checkstyle8.2.3重复规则
【用例描述】不需测试用例
【自测情况】本地静态检查通过

删除checkstyle8.2.3重复规则

---

.github/workflows/maven.yml
checkstyle.xml

【issue号/问题单号/需求单号】#457
【修改内容】
1. checkstyle增加忽略ut的配置
2. 代码静态检查调整报错级别为error
【用例描述】不需测试用例
【自测情况】本地静态检查通过

checkstyle增加不检测UT配置，规则报错级别调整为error

---

sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/main/java/com/huawei/dubbo/registry/utils/ReflectUtils.java
sermant-plugins/sermant-service-registry/dubbo-registry-plugin/src/test/java/com/huawei/dubbo/registry/ReflectUtilsTest.java
sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java

【issue号/问题单号/需求单号】 #455 
【修改内容】增加dubbo注册插件对group与version的支持
【用例描述】单元测试通过
【自测情况】本地自测通过
【影响范围】dubbo注册插件

【feature】增加dubbo注册插件对group与version的支持

---

docs/QuickStart.md
sermant-agentcore/sermant-agentcore-core/config/logback.xml
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/heartbeat/HeartbeatServiceImpl.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/send/NettyClient.java
sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java
sermant-backend/src/main/resources/logback.xml

【issue号/问题单号/需求单号】#430
【修改内容】
1. 框架日志发送方式由每个插件发送一条数据更改为所有插件统一发送一条数据
2. 日志路径修改为相对路径
【用例描述】暂不需测试用例
【自测情况】本地静态检查通过

心跳发送方式修改，日志路径修改

---

checkstyle.xml

【issue号/问题单号/需求单号】#461
【修改内容】降低getBytes检查（涉及非String.getBytes）、参数个数检查、捕获Exception异常的检查级别
【用例描述】不涉及
【自测情况】不涉及
【影响范围】不涉及

【fix】降低getBytes检查（涉及非String.getBytes）、参数个数检查、捕获Exception异常的检查级别

---

docs/FAQ.md
docs/QuickStart.md
docs/README.md

【issue号/问题单号/需求单号】#459
【修改内容】文档增加FAQ部分
【用例描述】不需测试用例
【自测情况】本地静态检查通过

参数问题说明和FAQ文档修改

---

checkstyle.xml

【issue号/问题单号/需求单号】#472
【修改内容】恢复ParameterNumber、IllegalThrows、ParameterAssignment、IllegalCatch的提示级别
【用例描述】不涉及
【自测情况】不涉及
【影响范围】不涉及

【fix】恢复ParameterNumber、IllegalThrows、ParameterAssignment、IllegalCatch的提示级别

---

pom.xml

【issue号/问题单号/需求单号】#474
【修改内容】backend模块添加默认编译标签
【用例描述】不需测试用例
【自测情况】本地静态检查通过

默认编译选项添加backend模块

---

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/converter/YamlConverter.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/entity/CseServiceMeta.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/MatchGroupResolver.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/resolver/AbstractResolver.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/FlowControlConfig.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/AlibabaDubboClusterInvoker.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/ApacheDubboClusterInvoker.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/DubboService.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/service/DubboRest4jServiceImpl.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/service/HttpRest4jServiceImpl.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/test/java/com/huawei/fowcontrol/res4j/handler/HandlerFacadeTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfig.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfigSyncer.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/context/RegisterContext.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/handler/SingleStateCloseHandler.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DiscoveryClientInterceptor.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/ServerListInterceptor.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/NacosHealthInterceptor.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/FieldAccessAction.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/CommonUtils.java

【issue号/问题单号/需求单号】#463
【修改内容】去除suppresschecktyle注解；添加部分日志
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控插件与注册插件

【fix】suppress-checkstyle去除

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/exception/DupConfIndexException.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/exception/DupServiceException.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/exception/SchemaException.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/common/DynamicConfigEvent.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/http/HttpResult.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/kie/KieClient.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperInitException.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/heartbeat/HeartbeatServiceImpl.java
sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/KieDynamicConfigServiceTest.java
sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/kie/PublishTest.java
sermant-agentcore/sermant-agentcore-premain/pom.xml
sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/common/BootArgsBuilder.java
sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/exception/DupPremainException.java
sermant-agentcore/sermant-agentcore-premain/src/main/java/com/huawei/sermant/premain/exception/InitPremainException.java

【issue号/问题单号/需求单号】#477
【修改内容】修改codecheck问题
【用例描述】不涉及
【自测情况】不涉及
【影响范围】不涉及

【fix】修改codecheck问题

---

pom.xml

【issue号/问题单号/需求单号】#474
【修改内容】默认编译选项添加package模块
【用例描述】不需测试用例
【自测情况】本地静态检查通过

默认编译选项添加package模块

---

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/ResolverManager.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/MatchGroupResolver.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/syncer/RuleDynamicConfigListener.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/CommonConst.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/util/ConvertUtils.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/util/StringUtils.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/AlibabaDubboClusterInvoker.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/cluster/ApacheDubboClusterInvoker.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/InterceptorSupporter.java

【issue号/问题单号/需求单号】#480
【修改内容】
1、流控配置扩展, 当前支持批量配置
2、流控新增支持dubbo泛化接口匹配
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控

【feature】流控支持批量配置模式并支持dubbo泛化接口调用

---

sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java

【issue号/问题单号/需求单号】#490
【修改内容】
core将心跳数据由插件单独发送更改为插件统一发送，因此写入kafka的心跳格式维持原有格式需要对backend写入kafka部分进行修改
【用例描述】不需测试用例
【自测情况】本地静态检查通过

心跳写入kafka格式修改

---

.github/workflows/create_release.yml

【issue号/问题单号/需求单号】#500
【修改内容】release出包actions中版本号添加单引号
【用例描述】不需测试用例
【自测情况】本地静态检查通过

【BUG】release发布支持更新版本号

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/entity/ExecuteContext.java

【issue号/问题单号/需求单号】#508
【修改内容】ExecuteContext中Field设置成员变量的值时指定被拦截类的对象
【用例描述】不涉及
【自测情况】不涉及
【影响范围】不涉及

【fix】Field设置成员变量的值时指定被拦截类的对象

---

docs/user-guide/backend.md

【issue号/问题单号/需求单号】#510
【修改内容】增加了backend模块缓存开关使用说明
【用例描述】不需测试用例
【自测情况】本地静态检查通过

添加backend缓存开关说明

---

checkstyle.xml

【issue号/问题单号/需求单号】#525
【修改内容】checkstyle检查报名规则由com.huawei*更改为com.huaweicloud*
【用例描述】不需测试用例
【自测情况】本地检查通过

checkstyle更改包名检查规则

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/strategy/LoadPropertiesStrategy.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/config/utils/ConfigValueUtil.java

【issue号/问题单号/需求单号】#527
【修改内容】
1.  从config.properties获取配置后增加set类型转换
2. 修改checkstyle
【用例描述】暂无用例
【自测情况】本地测试、UT测试通过
【影响范围】无

【fix】修复config.properties中agent.config.ignoredPrefixes参数不生效的bug

---

sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/entity/InterfaceData.java
sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/listener/GovernanceConfigListener.java
sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java

【issue号/问题单号/需求单号】 #538 
【修改内容】增加对tag参数的支持
【用例描述】单元测试通过
【自测情况】本地自测通过
【影响范围】dubbo注册插件

【feature】增加对tag参数的支持

---

sermant-plugins/pom.xml
sermant-plugins/sermant-dynamic-config/pom.xml
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegisterDynamicConfigSyncer.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/handler/SingleStateCloseHandler.java

【issue号/问题单号/需求单号】#542
【修改内容】
1、删除多余的pom配置
2、修复CSE不支持‘-’键配置问题，改为‘_’
3、原注册中心关闭改为懒关闭模式，基于心跳检测，避免类加载器问题影响
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】注册插件

【fix】注册开关相关问题修复

---

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DispatcherServletInterceptor.java

【issue号/问题单号/需求单号】#542
【修改内容】1、修复流控在宿主配置ContextPath路径匹配不正确的问题
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】流控插件

【fix】流控路径匹配问题修复

---

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java

【issue号/问题单号/需求单号】#548
【修改内容】流控拦截黑名单逻辑修复
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控插件

【fix】流控黑名单逻辑修复

---

docs/README.md
docs/dev-guide/dev_plugin_module.md

【issue号/问题单号/需求单号】#558
【修改内容】1、修改readme 2、修改dev_plugin_module
【用例描述】不涉及
【自测情况】不涉及
【影响范围】1、readme和插件模块开发手册修改

【fix】修改ReadMe和插件模块开发手册中与现有工程不符合的部分

---

sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java
sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/ConfigConstants.java
sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java

【issue号/问题单号/需求单号】#561
【修改内容】修正SpringCloud注册框架为Sermant
【用例描述】不涉及
【自测情况】本地测试通过
【影响范围】SpringCloud注册插件

【fix】修正SpringCloud注册框架为Sermant

---

sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java

【issue号/问题单号/需求单号】 #565 
【修改内容】修复注册时实例发送心跳时间间隔修改不生效的bug
【用例描述】单元测试通过
【自测情况】本地自测通过
【影响范围】dubbo注册插件

【bug】修复注册时实例发送心跳时间间隔修改不生效的bug

---

sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/pom.xml
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/config/RegistryConfigResolverTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/RegistryDelayInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/ResponseTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringCacheManagerInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringLoadbalancerFeignResponseInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringLoadbalancerRestTemplateResponseInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringLoadbalancerWarmUpInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringRibbonWarmUpInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringWebHandlerInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/SpringZuulResponseInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/grace/interceptors/WarmUpTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/interceptors/SpringFactoriesInterceptorTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/utils/CommonUtilsTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/utils/ReflectUtilsTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/test/java/com/huawei/registry/utils/ZoneUtilsTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/pom.xml
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/cache/AddressCacheTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/client/ScDiscoveryTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/impl/GraceServiceImplTest.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/test/java/com/huawei/registry/service/server/GraceHttpServerTest.java

【issue号/问题单号/需求单号】#579
【修改内容】补充优雅上下线UT
【用例描述】暂无用例
【自测情况】UT测试
【影响范围】优雅上下线功能

【document】补充优雅上下线UT

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java

【issue号/问题单号/需求单号】#580
【修改内容】修护环境变量和启动参数可能存在的优先级读取错误问题
【用例描述】暂无用例
【自测情况】UT测试
【影响范围】全局环境变量读取

【fix】修护环境变量和启动参数可能存在的优先级读取错误问题

---

docs/user-guide/feature-list.md
docs/user-guide/registry/dubbo-registry-migiration.md
docs/user-guide/registry/spring-cloud-registry-migiration.md

【issue号/问题单号/需求单号】 #590 
【修改内容】修改feature-list文档
【用例描述】不涉及
【自测情况】不涉及
【影响范围】不涉及

【fix】修改feature-list文档

---

sermant-agentcore/sermant-agentcore-config/config/logback.xml

【issue号/问题单号/需求单号】#599
【修改内容】删除日志模板颜色渲染部门
【用例描述】不需测试用例
【自测情况】本地静态检查通过
【影响范围】对用户使用无影响

【BUG】删除日志模版颜色渲染

---

sermant-plugins/sermant-router/router-demo/pom.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/pom.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/java/com/huaweicloud/router/spring/demo/ConsumerApplication.java
sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/java/com/huaweicloud/router/spring/demo/client/ProviderClient.java
sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/java/com/huaweicloud/router/spring/demo/controller/ConsumerController.java
sermant-plugins/sermant-router/router-demo/spring-router-demo/consumer-demo/src/main/resources/application.yml
sermant-plugins/sermant-router/router-demo/spring-router-demo/pom.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/pom.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/java/com/huaweicloud/router/spring/demo/ProviderApplication.java
sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/java/com/huaweicloud/router/spring/demo/controller/ProviderController.java
sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/resources/application.yml
sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/pom.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/src/main/java/com/huaweicloud/router/spring/demo/ZuulApplication.java
sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/src/main/resources/application.yml
sermant-plugins/sermant-router/router-demo/spring-router-demo/zuul-demo/src/test/java/com/huaweicloud/router/spring/demo/RouterTest.java

【issue号/问题单号/需求单号】 #587 
【修改内容】增加spring标签路由demo
【用例描述】暂无
【自测情况】UT通过
【影响范围】demo应用，不影响插件功能

【Feature】增加spring标签路由demo

---

sermant-plugins/sermant-service-registry/config/config.yaml
sermant-plugins/sermant-service-registry/registry-common/src/main/java/com/huawei/registry/config/RegisterConfig.java
sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/ServicecombServiceInstance.java

【issue号/问题单号/需求单号】#606
【修改内容】增加以IP地址替换域名的访问配置
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】spring注册

【fix】增加以IP地址替换域名的访问配置

---

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/ConfigConst.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DispatcherServletInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java

【issue号/问题单号/需求单号】#609
【修改内容】流控增加上游服务名传递
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】流控治理策略

【fix】流控增加上游服务传递，用于判断服务端治理策略

---

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/FeignRequestInterceptor.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/HandlerConstants.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/handler/CircuitBreakerRequestHandler.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/resources/META-INF/services/com.huawei.fowcontrol.res4j.chain.AbstractChainHandler

【issue号/问题单号/需求单号】#610
【修改内容】
1.修正feign请求熔断异常判断
2.调整熔断抛出异常的逻辑
3.关闭了熔断服务端能力（线上暂时不支持）
【用例描述】暂无用例
【自测情况】线上测试通过
【影响范围】流控治理

【fix】修正流控部分bug

---

checkstyle.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/consumer/Dockerfile
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/consumer/build.sh
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/consumer/start.sh
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/provider/Dockerfile
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/provider/build.sh
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/provider/start.sh
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/zuul/Dockerfile
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/zuul/build.sh
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/images/zuul/start.sh
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/consumer.yaml
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/gray-provider.yaml
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/provider.yaml
sermant-plugins/sermant-router/router-demo/spring-router-demo/deployment/k8s/zuul.yaml
sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/pom.xml
sermant-plugins/sermant-router/router-demo/spring-router-demo/provider-demo/src/main/java/com/huaweicloud/router/spring/demo/ProviderApplication.java

【issue号/问题单号/需求单号】 #587 
【修改内容】增加spring标签路由demo的部署文件
【用例描述】暂无
【自测情况】已自测
【影响范围】demo应用，不影响插件功能

【Feature】增加spring标签路由demo的部署文件

---

.github/workflows/create_release.yml

【issue号/问题单号/需求单号】#619
【修改内容】更改release版本号
【用例描述】不需用例
【自测情况】本地检查通过
【影响范围】对用户使用无影响

更新release版本号

---

docs/README.md
docs/dev-guide/Sermant去源码插件开发说明.md

【issue号/问题单号/需求单号】#612
【修改内容】
1.增加插件去源码开发文档；
2.增加中心仓发布说明文档；
【用例描述】不需用例
【自测情况】本地检查通过
【影响范围】对用户使用无影响

增加插件去源码开发说明

---

checkstyle.xml
suppressions.xml

What type of PR is this?
/checkstyle
Utility classes should not have a public or default constructor
Which issue(s) this PR fixes: https://github.com/huaweicloud/Sermant/issues/627
Fixes：update suppressions.xml
Use case description: No
Does this PR introduce a user-facing change?
No
Additional documentation e.g., usage docs, etc.:
No

[bug] update suppressions.xml

---

sermant-example/demo-flowcontrol/pom.xml
sermant-example/demo-flowcontrol/spring-rest-consumer/pom.xml
sermant-example/demo-flowcontrol/spring-rest-consumer/src/main/java/com/huaweicloud/flowcontrol/rest/consumer/FlowRestController.java
sermant-example/demo-flowcontrol/spring-rest-consumer/src/main/java/com/huaweicloud/flowcontrol/rest/consumer/RestConsumerApplication.java
sermant-example/demo-flowcontrol/spring-rest-consumer/src/main/resources/application.yml
sermant-example/demo-flowcontrol/spring-rest-provider/pom.xml
sermant-example/demo-flowcontrol/spring-rest-provider/src/main/java/com/huaweicloud/flowcontrol/rest/provider/FlowRestController.java
sermant-example/demo-flowcontrol/spring-rest-provider/src/main/java/com/huaweicloud/flowcontrol/rest/provider/RestProviderApplication.java
sermant-example/demo-flowcontrol/spring-rest-provider/src/main/resources/application.yaml
sermant-example/pom.xml

【issue号/问题单号/需求单号】#618
【修改内容】增加流控demo
【用例描述】不涉及
【自测情况】本地测试
【影响范围】无

【feature】流控demo提交

---

docs/dev-guide/Sermant去源码插件开发说明.md

【issue号/问题单号/需求单号】#630
【修改内容】删除文档pom文件描述中core模块打包重命名配置，与基于源码开发打包结果保持一致。
【用例描述】不需测试用例
【自测情况】本地检查通过
【影响范围】对用户使用无影响

插件去源码开发文档修改

---

docs/README.md
docs/user-guide/injector.md

【issue号/问题单号/需求单号】#624
【修改内容】新增容器化部署指导文档
【用例描述】无需用例
【自测情况】本地检查通过
【影响范围】对用户使用无影响

【document】容器化部署宿主应用自动挂载sermant-agent指导手册

---

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/entity/FlowControlResult.java
sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/enums/FlowControlEnum.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/HandlerChainEntry.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/HandlerConstants.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/handler/BulkheadRequestHandler.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/chain/handler/CircuitBreakerRequestHandler.java
sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/resources/META-INF/services/com.huawei.fowcontrol.res4j.chain.AbstractChainHandler

【issue号/问题单号/需求单号】#596 #635
【修改内容】修复熔断请求次数多统计问题；开放熔断服务端。
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】流控-熔断

【fix】修复熔断请求次数统计过多问题, 区分异常与结果, 分别统计

---

sermant-injector/src/test/resources/test.json

【issue号/问题单号/需求单号】#624
【修改内容】去除无用测试数据
【用例描述】暂无
【自测情况】本地UT测试通过
【影响范围】 无影响

【document】去除无用测试数据

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginManager.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginSystemEntrance.java
sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/config/PluginSetting.java

【issue号/问题单号/需求单号】#638
【修改内容】修复profile包含空格以及profile可能为null的问题
【用例描述】暂无用例
【自测情况】1. 测试场景：sermant-agent启动时测试plugin.yaml中profile为空以及包含空格的场景。2. 测试结果：正常运行
【影响范围】对框架和插件无影响

【bug】修复profile包含空格以及profile可能为null的问题

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/subscribe/processor/ConfigOrderIntegratedProcessor.java
sermant-plugins/sermant-router/router-common/src/main/java/com/huaweicloud/sermant/router/common/constants/RouterConstant.java
sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/RouterConfiguration.java
sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
sermant-plugins/sermant-router/router-config-common/src/test/java/com/huaweicloud/sermant/router/config/utils/RuleUtilsTest.java
sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/AbstractConfigHandler.java
sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/RouterConfigHandler.java
sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/handler/ServiceConfigHandler.java
sermant-plugins/sermant-router/router-config-service/src/main/java/com/huaweicloud/sermant/router/config/listener/RouterConfigListener.java

【issue号/问题单号/需求单号】 #587 
【修改内容】增加spring标签路由功能
【用例描述】暂无
【自测情况】本地自测通过启动spring-router-demo中的服务，然后执行zuul-demo中的UT，验证通过
【影响范围】新增功能，不影响其它插件

【Feature】修改标签路由功能解析配置的方式

---

docs/user-guide/flowcontrol/flowcontrol.md
docs/user-guide/loadbalancer/document.md

【issue号/问题单号/需求单号】#596
【修改内容】根据最新代码修改流控文档与负载均衡文档内容
【用例描述】不涉及
【自测情况】不涉及
【影响范围】无

【doc】流控文档与负载均衡文档修改

---

docs/dev-guide/dev_plugin_code.md

【修改内容】更新插件配置文件相关文档
【用例描述】无需用例
【自测情况】不涉及
【影响范围】插件开发文档

【doc】更新插件配置文件相关文档

---

sermant-plugins/sermant-service-registry/dubbo-registry-service/src/main/java/com/huawei/dubbo/registry/service/RegistryServiceImpl.java

【issue号/问题单号/需求单号】 #671 
【修改内容】修复dubbo注册时，有可能触发空指针的bug
【用例描述】暂无用例
【自测情况】本地测试，启动1个consumer（订阅2个接口），2个provider（其中一个provider发布一个接口，另一个provider发布2个接口），consumer能够成功消费，不会触发空指针
【影响范围】dubbo注册插件

【fix】修复dubbo注册时，有可能触发空指针的bug

---

.github/workflows/intergration_spring_test.yml
sermant-agentcore/sermant-agentcore-config/config/logback.xml

【issue号/问题单号/需求单号】#680
【修改内容】
1.修改cse软件包保留时间为1天
2.增加错误日志上传，如果测试错误，日志保留5天。日志包含应用日志与sermant日志
3.增加sermant相关变量可由环境变量指定
【用例描述】流水线用例
【自测情况】
1.本地针对sermant日志环境变量问题已测试无问题
2.自动化测试流水线已验证
【影响范围】sermant日志与spring测试流水线

【feature】针对spring自动化测试增加测试错误时的日志上传

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadYamlStrategy.java

【修改内容】修复yaml配置中boolean字段未配置时获取其他数据源参考值的解析问题
【用例描述】暂无用例
【自测情况】测试场景：config.yaml文件中未配置boolean类型字段，启动时 -D添加boolean字段对应的预设值。测试结果：解析正常
【影响范围】插件配置

【fix】修复yaml配置中boolean字段未配置时获取其他数据源参考值的解析问题

---

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/ServiceManager.java

【issue号/问题单号/需求单号】#677
【修改内容】修复关闭jvm时某个服务执行stop方法出现异常后续服务无法按预期关闭的问题
【用例描述】暂无用例
【自测情况】本地构造异常验证通过
【影响范围】插件服务

【fix】修复关闭jvm时某个服务执行stop方法出现异常后续服务无法按预期关闭的问题

---

sermant-plugins/sermant-monitor/config/config.yaml
sermant-plugins/sermant-monitor/monitor-service/pom.xml
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/CpuInfoCommand.java
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/command/DiskCommand.java
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/common/MemoryType.java
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/config/MonitorServiceConfig.java
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/JvmCollectorService.java
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/ServerCollectorService.java
sermant-plugins/sermant-monitor/monitor-service/src/main/java/com/huawei/monitor/service/SwitchService.java
sermant-plugins/sermant-monitor/monitor-service/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.config.PluginConfig

【issue号/问题单号/需求单号】#691
【修改内容】
1、增加插件开关配置  
2、修改G1等GC情况下指标采集。
【用例描述】暂无用例
【自测情况】
1、开关关闭后不执行指标采集，开启时进行指标次啊及
2、采用G1等GC情况下指标正常采集
【影响范围】1、sermant-monitor 监控插件

add monitor switch, add support other GC

---

sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegistrationProperties.java

【issue号/问题单号/需求单号】#688
【修改内容】修复dubbo应用开启spring注册出现类找不到的问题
【用例描述】暂无
【自测情况】
1.基于dubbo开启和未开启spring注册开关测试，是否存在类找不到问题
2.基于spring应用开启注册开关测试，测试调用是否正常
【影响范围】dubbo应用开启spring注册

【fix】修复dubbo应用开启spring注册出现类找不到的问题

---

pom.xml
sermant-backend/pom.xml

【issue号/问题单号/需求单号】#673
【修改内容】
(1)根pom文件release编译选项增加backend模块
(2)backend模块pom文件增加agent和release编译选项，在agent编译时才会触发更改输出目录
【用例描述】未修改代码，不需测试用例
【自测情况】本地测试通过，正常发布包到中心仓
【影响范围】对用户的使用没有影响

增加backend发布中心仓

---

sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/UrlInterceptorTest.java
sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/cache/DubboLoadbalancerCacheTest.java
sermant-plugins/sermant-loadbalancer/dubbo-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/cache/RuleManagerHelper.java
sermant-plugins/sermant-loadbalancer/loadbalancer-service/pom.xml
sermant-plugins/sermant-loadbalancer/loadbalancer-service/src/test/java/com/huaweicloud/loadbalancer/YamlRuleConverterTest.java
sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/main/java/com/huaweicloud/loadbalancer/cache/RibbonLoadbalancerCache.java
sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/ClientFactoryInterceptorTest.java
sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/LoadBalancerInterceptorTest.java
sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/RibbonLoadBalancerInterceptorTest.java
sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/RuleManagerHelper.java
sermant-plugins/sermant-loadbalancer/spring-cloud-loadbalancer-plugin/src/test/java/com/huaweicloud/loadbalancer/cache/RibbonLoadbalancerCacheTest.java

【issue号/问题单号/需求单号】#596
【修改内容】负载均衡插件UT测试间存在依赖关系，整体测试会因为互相关联导致UT失败，主要针对该问题修复；同时针对mock及时关闭，防止多个ut相互影响
【用例描述】不涉及
【自测情况】UT测试通过
【影响范围】无

【fix】修正并添加负载均衡插件UT

---

sermant-package/Dockerfile

【issue号/问题单号/需求单号】https://github.com/huaweicloud/Sermant/issues/695
【修改内容】删除了多余Dockerfile文件
【用例描述】不涉及测试用例
【自测情况】不涉及测试用例
【影响范围】无影响

[fix] delete Dockerfile in sermant-package

---

javamesh-package/Dockerfile

【issue号/问题单号/需求单号】#695
【修改内容】删除了多余Dockerfile文件
【用例描述】不涉及测试用例
【自测情况】不涉及测试用例
【影响范围】无影响

[fix] delete Dockerfile in javamesh-package
