javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/config/CommonLoadConfigStrategy.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/ConfigDupIndexException.java
【issue号】#73
【修改原因】统一配置中，使用同一个键解释其值时发生死循环
【修改内容】直接抛出异常，而不是任他栈溢出
【检查者】@fuziye01 @3838438abcd @xuezechao-hub
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】统一配置系统
=> 【bug修复】修复统一配置中使用同一个键解释其值时发生死循环的问题

.github/workflows/maven.yml
【issue号】#86
【修改原因】
1. 仓库没有自动构建出包能力
【修改内容】
1. 添加actions配置文件
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】
1. 支持个人fork CI构建
2. 支持合入master分支构建
=> 【CI】添加actions配置，开启github自动构建功能

javamesh-samples/javamesh-flowrecord/flowrecord-plugin/pom.xml
【issue号】#91
【修改原因】
1. 录制插件存在多余依赖配置
【修改内容】
1. pom文件删除backend依赖配置
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】无影响
=> 【bug】录制插件删除多余依赖

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/enhancer/AbstractAroundEnhancer.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/enhancer/InstanceMethodEnhancer.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/agent/enhancer/StaticMethodEnhancer.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/BizException.java, javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/DubboInterceptor.java, javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/exception/FlowControlException.java
【issue号】#89
【修改原因】流控插件存在需抛出异常到业务层的场景，此处只针对流控生效；针对这块抽象业务异常，提供其他有类似场景插件业务异常抛出入口
【修改内容】
1、新增BizException，所有需抛出业务异常的插件端，均需要继承该类；
2、定义在core的FlowControlException已迁移到流控插件
【检查者】@beetle-man @fuziye01 @xuezechao-hub @HapThorin
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】流控能力
=> 【功能】抽出抛出业务异常入口

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/exception/IllegalConfigException.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/plugin/config/PluginConfigManager.java, javamesh-samples/javamesh-example/demo-application/pom.xml, javamesh-samples/javamesh-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoConfigInterceptor.java, javamesh-samples/javamesh-example/demo-service/src/main/java/com/huawei/example/demo/service/DemoComplexServiceImpl.java, javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/config/KafkaConnectBySslSwitch.java, javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/util/PluginConfigUtil.java, javamesh-samples/javamesh-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/core/util/ZookeeperConnectionEnum.java, javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/utils/PluginConfigUtil.java, javamesh-samples/javamesh-route/label-plugin/src/main/java/com/huawei/route/label/LabelInitServiceImpl.java, javamesh-samples/javamesh-route/report-plugin/src/main/java/com/huawei/route/report/ReporterPluginInitServiceImpl.java
【issue号】#112
【修改原因】插件配置文件不存在时获取到的插件配置对象为空
【修改内容】修复插件配置文件不存在时获取到的插件配置对象为空的问题
【检查者】@fuziye01 @3838438abcd @xuezechao-hub @beetle-man
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】所有插件获取配置的api调整为PluginConfigManager#getPluginConfig @3838438abcd @xuezechao-hub @beetle-man
=> 【bug修复】修复插件配置文件不存在时获取到的插件配置对象为空的问题

javamesh-agentcore/javamesh-agentcore-core/pom.xml, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/AgentCoreEntrance.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/common/PathIndexer.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/log/LogBackInit.java, javamesh-agentcore/javamesh-agentcore-core/src/main/resources/config/logback.xml, javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/BootArgsBuilder.java, javamesh-agentcore/javamesh-agentcore-premain/src/main/java/com/huawei/apm/premain/common/PathDeclarer.java
【issue号】#114
【修改原因】
1. premain模块 和 core 模块采用不同的日志实现
2. 日志配置无法统一管理，无法出包后进行修改
【修改内容】
1. core模块采用jul-to-slf4j桥接包将jul日志交由slf4j管理
2. core模块采用logback实现slf4j日志接口
3. 编译后config目录添加logback配置文件
4. 框架日志输出目录为java-mesh目录下logs目录，按照级别，日期进行分类。
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】
1. premain模块日志输出到文件中
2. core日志在控制台和文件中同步打印
=> 框架日志采用logback统一

javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/domain/HttpRequestEntity.java, javamesh-samples/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/http/v4/HttpServerInterceptor.java
【issue号】#116
【修改原因】
1. 录制插件流量入参录制错误
【修改内容】
1. 录制插件流量请求体格式由string改为 map
2. 入参录制改为调用获取请求参数api
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】
1. 录制插件录制流量请求体类型由string改为map
2. 录制插件获取请求参数方式修改
=> 解决录制插件录制流量入参错误的问题

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/core/monitor/MonitorReportServiceImpl.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/apm/core/lubanops/core/trace/TraceReportServiceImpl.java, javamesh-agentcore/javamesh-agentcore-core/src/main/proto/Message.proto, javamesh-agentcore/javamesh-agentcore-premain/src/main/resources/config/bootstrap.properties, javamesh-backend/pom.xml, javamesh-backend/src/main/java/com/huawei/apm/backend/common/conf/KafkaConf.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/Address.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/AddressScope.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/AddressType.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/HeartBeatResult.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/MonitorItem.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/Protocol.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/RegisterResult.java, javamesh-backend/src/main/java/com/huawei/apm/backend/entity/Result.java, javamesh-backend/src/main/java/com/huawei/apm/backend/server/HttpServer.java, javamesh-backend/src/main/java/com/huawei/apm/backend/server/ServerHandler.java, javamesh-backend/src/main/java/com/huawei/apm/backend/util/RandomUtil.java, javamesh-backend/src/main/proto/Message.proto, javamesh-backend/src/main/resources/application.properties, pom.xml
【issue号】#120
【修改原因】
1. 框架启动后luban注册，数据发送等功能连不上服务器报错
【修改内容】
1. backend模块实现luban注册和心跳接口，在框架启动之后模拟luban后端接受注册和心跳的请求。
2. luban监控和链路数据发送由websocket发送改为统一消息模块发送，原luban逻辑暂时保留，
3. boostrap配置文件服务器地址端口修改
4. example打包中加入backend模块
【用例描述】暂无
【自测情况】本地测试通过
【影响范围】
1. backend模块添加了两个http请求接口
2. luban监控和链路数据通过统一消息模块发往backend，写入kafka
=> 启动后luban报错问题修改

.github/workflows/maven.yml, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/lubanops/core/transfer/dto/heartbeat/HeartbeatMessage.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/heartbeat/HeartbeatService.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/service/heartbeat/HeartbeatServiceImpl.java, javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/AgentInfo.java, javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/PluginInfo.java, javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/HttpServer.java
【issue号/问题单号/需求单号】#154
【修改原因】
原因一：core模块心跳没有版本信息
原因二：插件心跳信息增加了版本字段，需要对查询插件信息接口做调整
原因三：develop和master以外的分支推动代码不会触发门禁
【修改内容】
增加了core模块心跳版本字段；
增加了录制插件名称和版本字段；
修改了backend查询插件信息的接口。
修改了门禁触发条件。
【检查者】@fuziye01 @HapThorin 
【用例描述】暂无用例
【自测情况】
1. 本地测试通过。
2. 本地启动zk, kafka，通过postman调用查询接口，正确返回插件信息。
【影响范围】
1. 框架心跳增加版本字段
2. 录制插件增加名称和版本字段
=> core心跳添加版本字段，查询插件信息接口修改

javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/DefaultHttpClientDefinition.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/PathVarDefinition.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/DefaultHttpClientInterceptor.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/PathVarInterceptor.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientService.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/PathVarService.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/context/FeignResolvedURL.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientServiceImpl.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/PathVarServiceImpl.java
【issue号/问题单号/需求单号】
【修改原因】
原因： 开发过程中更改灰度应用请求ip拦截点、获取feign请求的url参考了skywalk代码，需要添加copyright。
【修改内容】
增加了ASF
【检查者】@yangyshdan @HapThorin @fuziye01
【用例描述】不需要测试用例
【自测情况】本地测试通过
【影响范围】无影响
=> 添加asf copyright

javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/DefaultHttpClientDefinition.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/definition/PathVarDefinition.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/DefaultHttpClientInterceptor.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/interceptor/PathVarInterceptor.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientService.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-plugin/src/main/java/com/huawei/gray/feign/service/PathVarService.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/context/FeignResolvedURL.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/DefaultHttpClientServiceImpl.java, javamesh-plugins/javamesh-route/gray-feign-http-9.x-service/src/main/java/com/huawei/gray/feign/service/PathVarServiceImpl.java
【issue号/问题单号/需求单号】
【修改原因】
原因： 开发过程中获取feign请求的url参考了skywalking，并在更改灰度应用请求ip的代码中使用到了feign请求的url，需要添加ASF copyright。
【修改内容】
增加了ASF copyright
【检查者】@yangyshdan @HapThorin @fuziye01
【用例描述】不需要测试用例
【自测情况】本地测试通过
【影响范围】无影响
=> 为feign灰度发布模块中使用或修改SkyWalking源码的类添加Apache Software Foundation (ASF)头信息

javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/dubbo/AliDubboInterceptor.java, javamesh-plugins/javamesh-flowrecord/flowrecord-plugin/src/main/java/com/huawei/flowrecord/plugins/dubbo/DubboInterceptor.java
【issue号/问题单号/需求单号】
【修改原因】原因一：未添加ASF
【修改内容】增加了ASF
【检查者】@yangyshdan @HapThorin @fuziye01 
【用例描述】无需测试用例
【自测情况】未修改代码
【影响范围】无
=> 为流量录制模块中使用或修改skywalking源码的类添加Apache Software Foundation (ASF)头信息

javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/AnnotationMatcher.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/ClassMatcher.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/MultiClassMatcher.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/NameMatcher.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/NonNameMatcher.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/PrefixMatcher.java, javamesh-agentcore/javamesh-agentcore-core/src/main/java/com/huawei/javamesh/core/agent/matcher/SuperTypeMatcher.java, javamesh-plugins/javamesh-server-monitor/server-monitor-service/src/main/java/com/huawei/javamesh/sample/servermonitor/provider/OpenJvmMetricProvider.java
【修改原因】ASF版权信息补充
【修改内容】ASF版权信息补充
【检查者】@fuziye01 @HapThorin @xuezechao-hub @justforstudy-A
【用例描述】不涉及
【自测情况】不涉及
【影响范围】无
=> 为核心模块和监控插件模块中使用或修改skywalking源码的类添加Apache Software Foundation (ASF)头信息

LICENSE
【需求单号】#229
【修改内容】整理LICENSE文件中拷贝信息的格式：从Sentinel开始格式错误，缺少of；另外，项目说明的两行应当合成一行
【用例描述】不涉及
【自测情况】不涉及
【影响范围】LICENSE文件
=> 【doc】整理LICENSE文件中拷贝信息的格式

javamesh-backend/src/main/java/com/huawei/javamesh/backend/entity/PublishConfigEntity.java, javamesh-backend/src/main/java/com/huawei/javamesh/backend/server/HttpServer.java, javamesh-backend/src/main/java/com/huawei/javamesh/backend/util/BackendThreadFactory.java
【issue号/问题单号/需求单号】#223
【修改内容】backend模块增加配置接口： POST /sermant/publishConfig
【用例描述】门禁暂未配置zk等环境。
【自测情况】
- 本地测试通过
- 本地启动zk配置中心，通过postman调用增加配置接口。
【影响范围】
- 使用者可通过backend模块提供的接口修改配置中心配置
=> backend增加修改配置接口

sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/sample/monitor/common/collect/CollectTask.java, sermant-plugins/sermant-server-monitor/monitor-common/src/main/java/com/huawei/sermant/sample/monitor/common/utils/CommonUtil.java, sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/collector/CpuMetricCollector.java, sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/collector/DiskMetricCollector.java, sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/collector/NetworkMetricCollector.java, sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/command/CommandExecutor.java, sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/command/CommonMonitorCommand.java, sermant-plugins/sermant-server-monitor/server-monitor-service/src/main/java/com/huawei/sermant/sample/servermonitor/provider/OpenJvmMetricProvider.java
【issue号/问题单号/需求单号】#15
【修改内容】1、补充日志、参数校验 2、Linux命令执行器执行方法在返回结果前增加等待错误流处理线程的逻辑
【用例描述】不涉及
【自测情况】自测通过
【影响范围】server 监控
=> 错误日志和校验参数补充

docs/dev-guide/dev_plugin_code.md, docs/dev-guide/dev_plugin_module.md, pom.xml, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/classloader/PluginClassLoader.java, sermant-plugins/sermant-example/demo-service/pom.xml, sermant-plugins/sermant-example/demo-service/src/main/java/com/huawei/example/demo/service/DemoComplexServiceImpl.java
【问题单号】#245
【修改内容】
1.修复复杂插件服务start方法中使用的第三方依赖的slf4j api错误的问题
1.1.现在shade插件默认修正byte-buddy包和slf4j包
1.2.现在插件类加载器将会过滤掉com.huawei开头的类，他们将优先使用AppClassLoader加载
1.3.示例插件的复杂插件服务示例中模仿使用slf4j
1.4.同步更新开发文档
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】插件服务
=> 【Fix】修复复杂插件服务start方法中使用的第三方依赖的slf4j api错误的问题

.github/workflows/stale.yml
【需求单号】#260
【修改内容】增加自动关闭issue和pr的工作流，暂定过期时间为30天，第29天提醒，第30天关闭，每天凌晨4点执行(格林威治时间20点)
【用例描述】不涉及
【自测情况】测试有效：
自动调度测试：https://github.com/HapThorin/Sermant/actions/runs/1600173019
调度效果测试：https://github.com/HapThorin/Sermant/pull/3
测试中发现，github schedule 延迟较大，10分钟-20分钟左右
【影响范围】github工作流
=> 【workflow】增加自动关闭issue和pr的工作流，暂定过期时间为30天，第29天提醒，第30天关闭，每天凌晨4点执行(格林威治时间20点)

sermant-agentcore/sermant-agentcore-core/src/main/resources/config/all/plugins.yaml, sermant-agentcore/sermant-agentcore-core/src/main/resources/config/plugins.yaml, sermant-plugins/pom.xml, sermant-plugins/sermant-register-center/config/config.yaml, sermant-plugins/sermant-register-center/pom.xml, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/pom.xml, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/DiscoveryClientEnhancer.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/RegistrationEnhancer.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/ServerListEnhancer.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/DiscoveryClientInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/RegistrationInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/ServerListInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/services/RegisterCenterService.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.agent.definition.EnhanceDefinition, sermant-plugins/sermant-register-center/spring-cloud-register-service/pom.xml, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/config/RegisterConfig.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/impl/RegisterCenterServiceImpl.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/Register.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/RegisterManager.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/register/ScRegister.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/utils/CommonUtils.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/resources/META-INF/services/com.huawei.register.service.register.Register, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.config.PluginConfig, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/resources/META-INF/services/com.huawei.sermant.core.plugin.service.PluginService
【issue号】 #256
【修改内容】基于Agent实现拦截SpringCloud逻辑替换为SC注册中心实现
【检查者】@fuziye01 @HapThorin @beetle-man @xuezechao1 @provenceee
【用例描述】无
【自测情况】本地自测通过
【影响范围】新增功能，不对其他模块产生影响
=> 【feature】SpringCloud 注册中心替换为SC实现

sermant-backend/pom.xml
【issue号/问题单号/需求单号】#262
【修改内容】删除了backend模块日志配置的中文注释
【用例描述】暂不需用例
【自测情况】1、本地检查通过
【影响范围】无
=> 【bug】解决backned日志中文注释解析失败导致backned启动失败问题

.github/workflows/stale.yml
【问题单号】#269
【修改内容】自动关闭issue和pr的工作流调整
1、现在issue和pr扫描拆分成两步
2、据统计，Sermant目前每月新建的issue数量为60+，因此，调整处理阈值为80
3、考虑到pr处理应当比issue要及时，因此把不活跃时间判定为调整为半个月，处理阈值暂使用默认值30
【用例描述】不涉及
【自测情况】不涉及
【影响范围】过期issue和pr
=> 【perf】自动关闭issue和pr的工作流调整

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/KieDynamicConfigService.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/http/DefaultHttpClient.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/http/HttpClient.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/kie/KieClient.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/client/kie/KieListenerWrapper.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/constants/KieConstants.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/listener/KvDataHolder.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/kie/listener/SubscriberManager.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/utils/LabelGroupUtils.java, sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/BaseTest.java, sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/KieDynamicConfigServiceTest.java, sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/dynamicconfig/kie/PublishTest.java
【issue号/问题单号/需求单号】#311
【修改内容】
1、修复KIE发布配置存在相同key报错问题，存在相同的key转为更新值
2、重构KIE对单个key监听机制，增加group的单个key进行监听能力
3、修复在增加单个key时，group不规范时的处理
4、新增移除单个配置的方法实现
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】使用配置中心的模块：灰度发布、注册中心迁移@provenceee； 流控模块
=> 【Fix】KIE配置中心修复发布配置逻辑

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/dynamicconfig/zookeeper/ZooKeeperDynamicConfigService.java
【问题单号】#312
【修改内容】修复zk动态配置实现中遍历子节点时带有'/'的问题
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】动态配置系统zk实现
=> 【BUG】修复zk动态配置实现中遍历子节点时带有'/'的问题

sermant-plugins/sermant-flowcontrol/flowcontrol-service/pom.xml, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/context/RegisterContext.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/enhancers/IClientConfigEnhancer.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/handler/SingleStateCloseHandler.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/IClientConfigInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/EurekaHealthInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/NacosHealthInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/java/com/huawei/register/interceptors/health/ZookeeperHealthInterceptor.java, sermant-plugins/sermant-register-center/spring-cloud-register-plugin/src/main/resources/META-INF/services/com.huawei.sermant.core.agent.definition.EnhanceDefinition, sermant-plugins/sermant-register-center/spring-cloud-register-service/pom.xml, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/client/ScClient.java, sermant-plugins/sermant-register-center/spring-cloud-register-service/src/main/java/com/huawei/register/service/impl/RegisterCenterServiceImpl.java
【issue号/问题单号/需求单号】#315
【修改内容】
1、兼容nacos高版本健康检查
2、兼容consul高版本健康检查
3、修复低版本注册中心日志桥接问题，避免使用宿主日志，导致应用无法启动
4、修复流控在低版本yaml获取不到的问题
5、修复Eureka健康检查可能出现的空指针问题
6、针对关闭注册中心，进行统一异常处理，针对关闭失败的场景进行关闭状态重置
7、增加拦截获取服务基本信息的增强点，以便于在注册发现时无法获取服务名的问题
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】流控与注册中心-spring插件
=> 【Fix】修复流控与注册中心插件bug

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/matcher/ClassMatcher.java
【issue号/问题单号/需求单号】#337
【修改内容】修复拦截带有子类的方法时，匹配会将反省加加入superclass
【用例描述】暂不需测试用例
【影响范围】1、对用户的使用没有影响）
=> 【BUG】修复拦截带有子类的方法时，匹配会将反省加加入superclass

sermant-plugins/sermant-flowrecord/flowrecord-replay/flowrecord-console/pom.xml, sermant-plugins/sermant-flowrecord/flowrecord-replay/pom.xml
【issue号/问题单号/需求单号】#347
【修改内容】
1.录制插件回放模块spring依赖版本修改
2.flowrecord-console模块添加spring-context依赖
【用例描述】暂不需用例
【自测情况】1、本地静态检查通过，可编译，可运行
【影响范围】1、使用录制插件的用户可以正常编译运行flowreplay模块
=> 【BUG】录制插件回访模块依赖报错问题修复

sermant-backend/src/main/java/com/huawei/sermant/backend/cache/HeartbeatCache.java, sermant-backend/src/main/java/com/huawei/sermant/backend/common/conf/KafkaConf.java, sermant-backend/src/main/java/com/huawei/sermant/backend/server/HttpServer.java, sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java, sermant-backend/src/main/resources/application.properties
【issue号/问题单号/需求单号】#349
【修改内容】backend增加心跳数据缓存
【用例描述】暂不需用例
【影响范围】1、入门用户不需部署kafka即可在前端界面看到框架和插件运行状态
=> backend添加心跳数据缓存，不强依赖kafka

sermant-plugins/sermant-register-center/dubbo-register-plugin/pom.xml, sermant-plugins/sermant-register-center/dubbo-register-service/pom.xml
【issue号/问题单号/需求单号】 #373 
【修改内容】修复dubbo注册插件加载配置类与找不到guava类的bug
【检查者】@fuziye01 @HapThorin @beetle-man @xuezechao1 @justforstudy-A
【用例描述】单元测试通过
【自测情况】本地测试通过
【影响范围】注册插件
=> 【fix】修复dubbo注册插件加载配置类与找不到guava类的bug

.github/workflows/create_release.yml
【issue号/问题单号/需求单号】#389
【修改内容】增加了release发布actions
【用例描述】不需测试用例
【影响范围】1、需要发布release时通过执行 `git tag -a "${tag-name}" -m "${release-message}"` 创建tag，执行 `git push --tags` 即可出发release发布
=> actions 添加 release版本发布

pom.xml, sermant-agentcore/sermant-agentcore-core/pom.xml, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/ExtractService.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/InjectService.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/TracingService.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/TracingServiceImpl.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/SourceInfo.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/SpanEvent.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/SpanEventContext.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/TargetInfo.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/common/TracingRequest.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/sender/TracingMessage.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/sender/TracingMessageHeader.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/service/tracing/sender/TracingSender.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/utils/TracingUtils.java, sermant-agentcore/sermant-agentcore-core/src/main/resources/META-INF/services/com.huawei.sermant.core.service.BaseService, sermant-agentcore/sermant-agentcore-core/src/test/java/com/huawei/sermant/core/service/tracing/TracingServiceImplTest.java, sermant-plugins/sermant-flowcontrol/flowcontrol-demos/pom.xml
【issue号/问题单号/需求单号】#328
【修改内容】在service中新增链路追踪服务
【用例描述】1、provider场景跨度span测试 2、consumer场景跨度span测试 3、内部工作跨度场景span测试
【自测情况】1、静态检查通过；2、门槛用例通过；3、UT行覆盖86%；4、本地自测
【影响范围】1、新增插件时，需要添加链路追踪生命周期 2、需更新链路追踪服务代码
=> 【feature】agent-core新增链路追踪服务

docs/user-guide/flowcontrol/flowcontrol.md, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/CommonConst.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestDeclarer.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/HttpRequestInterceptor.java
【issue号/问题单号/需求单号】#470
【修改内容】
1、修复流控dubbo2.7.3-2.7.4出现的空指针问题
2、优化HTTP请求重试拦截点，避免拦截多个interceptor
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】流控插件
=> 【fix】修复流控dubbo2.7.3-2.7.4出现的空指针问题

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huawei/sermant/core/plugin/agent/BufferedAgentBuilder.java
【issue号/问题单号/需求单号】#494
【修改内容】1、修复增强启动类加载器加载类会被添加static块导致redefine抛出异常的问题
【用例描述】不涉及
【自测情况】1、本地静态检查清理情况；2、基线测试用例已过
【影响范围】不涉及
=> 【fix】修复增强启动类加载器加载类会被添加static块导致redefine抛出异常的问题

sermant-backend/src/main/java/com/huawei/sermant/backend/server/NettyServer.java, sermant-backend/src/main/java/com/huawei/sermant/backend/server/ServerHandler.java, sermant-backend/src/test/java/com/huawei/sermant/backend/NettyServerTest.java
【issue号/问题单号/需求单号】#506
【修改内容】修复没有kafka服务时，backend数据处理阻塞问题
【用例描述】不需测试用例
【自测情况】本地静态检查通过
【影响范围】用户在使用sermant时，bakcend中开启心跳缓存，则不用必须启动kafka服务。
=> 【BUG】修复没有kafka服务时，backend数据处理阻塞问题

sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/ResolverManager.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/match/BusinessMatcher.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/resolver/AbstractResolver.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/AbstractRule.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/BulkheadRule.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/CircuitBreakerRule.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/Configurable.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/RateLimitingRule.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/adapte/cse/rule/RetryRule.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/pom.xml, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/config/SpringEnvironmentInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/handler/DefaultRetryPredicateCreator.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DiscoveryClientDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DiscoveryClientServiceInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/services/RegisterCenterService.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/impl/RegisterCenterServiceImpl.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/Register.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/RegisterManager.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/register/ScRegister.java
【issue号/问题单号/需求单号】#533
【修改内容】
1、修复spring注册应用跨app调用场景兼容
2、增加流控默认的重试状态码与重试异常，与线上保持一致
3、流控插件支持读取spring应用配置文件流控规则
4、修改注册插件支持最新SpringCloud版本
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】注册插件与流控插件
=> 【fix】修复测试用例发现的部分问题 

sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
【issue号/问题单号/需求单号】#541
【修改内容】在双注册后，如果sc注册中心没有对应下游的实例，会直接抛出异常，导致查询实例流程终止，以至于调用中断
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】spring双注册
=> 【fix】修复双注册时因从sc查询不到实例导致无法调用的问题

sermant-agentcore/sermant-agentcore-core/pom.xml, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/config/SpringEnvironmentInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/ServerListInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/MarkUtils.java
【issue号/问题单号/需求单号】#542
【修改内容】
1、修复因agentCore引入spi依赖导致宿主加载找不到MessageBodyReader类的问题
2、修复流控插件低版本配置源无Stream问题，改为使用迭代器
3、修复ServerList存在无法获取服务名的问题，对于嵌套调用，限制只对最上层进行拦截合并实例
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控与注册插件
=> 【fix】修复流控与注册插件部分问题

sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/interceptors/SpringEnvironmentInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/config/SpringEnvironmentInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ZookeeperIndicatorDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/handler/SingleStateCloseHandler.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/ConsulHealthInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/EurekaHealthInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/NacosHealthInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/ZookeeperHealthInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/health/ZookeeperIndicatorInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/support/RegisterSwitchSupport.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.agent.declarer.PluginDeclarer, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScDiscovery.java
【issue号/问题单号/需求单号】#546
【修改内容】
1、优化双注册因cse无下游实例而不断输出错误日志问题，第一次使用info级日志提示，后续定时器则将日志级别定为优先级更低的fine
2、修复流控与动态配置插件1.x版本springboot无法获取服务名的问题
3、原注册中心关闭逻辑优化，当采用单注册时，默认第一次心跳即关闭原注册中心客户端心跳
【用例描述】暂无用例
【自测情况】本地测试通过
【影响范围】注册插件
=> 【fix】优化双注册时实例查询不到时的日志优化

sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/AlibabaDubboInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/ApacheDubboInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/AlibabaDubboInvokerInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/retry/ApacheDubboInvokerInterceptor.java, sermant-plugins/sermant-flowcontrol/flowcontrol-plugin/src/main/java/com/huawei/flowcontrol/service/InterceptorSupporter.java
【issue号/问题单号/需求单号】#548
【修改内容】流控插件兼容alibaba dubbo在调用时下游invoker的场景
【用例描述】暂无用例
【自测情况】本地自测通过
【影响范围】流控插件
=> 【fix】兼容在alibaba dubbo在2.6.6-2.6.12版本区间其invocation的invoker为空的场景

sermant-agentcore/sermant-agentcore-config/config/all/plugins.yaml, sermant-agentcore/sermant-agentcore-config/config/plugins.yaml, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/common/CommonConstant.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginSystemEntrance.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/config/PluginSetting.java
【issue号/问题单号/需求单号】#597
【修改内容】
1. 插件配置文增加场景与插件的映射配置(目前有cse场景)；
2. 插件配置文件增加场景参数(默认cse场景)；
3. 插件加载场景值支持启动命令-Dprofile=***指定；
4. 场景参数与插件参数不冲突，配置文件中场景参数与命令行场景参数不冲突，三者存在的话取插件交集进行加载。
【用例描述】不需测试用例
【自测情况】本地静态检查通过。
【影响范围】
1. 用户可以根据自己的需要选择使用场景，在配置文件中或者命令行指定场景；
2. 无使用场景的用户，不需进行修改。
=> 【feature】插件加载增加场景参数配置，支持通过-D指定场景名

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/service/dynamicconfig/utils/LabelGroupUtils.java
【issue号/问题单号/需求单号】 #604 
【修改内容】修复监听KIE配置时，无法监听env为空的配置
【用例描述】暂无
【自测情况】本地自测通过
【影响范围】动态配置
=> 【fix】修复监听KIE配置时，无法监听env为空的配置

checkstyle.xml, suppressions.xml
What type of PR is this?
/checkstyle 
**Utility classes should not have a public or default constructor**
Which issue(s) this PR fixes: #627 
Fixes： 
1.  Suppress for any classes that contain method named "main"
2. Suppress for any classes that are annotated with "SpringBootApplication"
Use case description: No
Does this PR introduce a user-facing change?
No
Additional documentation e.g., usage docs, etc.:
No
=>  [Bug] fix HideUtilityClassConstructor check to skip main method and SpringBootApplication annotation check

checkstyle.xml, suppressions.xml
What type of PR is this?
/checkstyle
Utility classes should not have a public or default constructor
Which issue(s) this PR fixes: https://github.com/huaweicloud/Sermant/issues/627
Fixes：add files in suppressions.xml
Use case description: No
Does this PR introduce a user-facing change?
No
Additional documentation e.g., usage docs, etc.:
No
=> [bug] add files in suppressions.xml

sermant-injector/scripts/certificate_k8s_1.19+/certificate.sh, sermant-injector/scripts/certificate_k8s_1.21-/certificate.sh
【issue号/问题单号/需求单号】#624
【修改内容】修复删除命名空间后证书失效的问题
【用例描述】暂无用例
【自测情况】删除sermant-injector的命名空间后重新执行脚本证书可用
【影响范围】不影响框架本身以及插件
=> 【bug】修复删除命名空间后证书失效的问题

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/PluginManager.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/adaptor/AdaptorManager.java
【issue号/问题单号/需求单号】#638
【修改内容】捕获启动时插件加载过程中的异常，使其不影响其他插件的加载和agent的运行
【用例描述】暂无用例
【自测情况】
1. 测试条件：sermant-agent加载两个以上插件，对其中一个插件构造异常。
2. 测试步骤：启动宿主应用挂载sermant-agent。
3. 预期结果：异常插件不影响其他插件的加载，agent正常运行
【影响范围】解决用户加载多个插件可能出现的加载失败问题
=> 【bug】修复加载某个插件过程发生异常导致整个agent启动失败的问题

sermant-backend/pom.xml
【issue号/问题单号/需求单号】#642
【修改内容】
backend模块pom文件中指定repackage的版本。
【用例描述】不需测试用例
【自测情况】
本地检查通过：
检查方式：(1) 执行 mvn package -P backend. (2) 命令执行成功，在项目根目录出现backend模块 jar包。
【影响范围】对用户的使用有没有影响
=> 【BUG】backend模块指定repackage版本

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/collector/PluginCollectorManager.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/plugin/agent/declarer/PluginDeclarer.java, sermant-example/demo-application/src/main/java/com/huawei/example/demo/DemoApplication.java, sermant-example/demo-application/src/main/java/com/huawei/example/demo/service/DemoCheckEnableService.java, sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/declarer/DemoCheckEnableDeclarer.java, sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/interceptor/DemoCheckEnableInterceptor.java, sermant-example/demo-plugin/src/main/resources/META-INF/services/com.huaweicloud.sermant.core.plugin.agent.declarer.PluginDeclarer
【issue号/问题单号/需求单号】#646
【修改内容】
1. PluginDeclarer增加isEnable()方法，插件可以实现该方法用于控制自身定义的PluginDeclarer是否需要被框架进行字节码增强。默认值为true
2. 增加demo方法用于验证上述开关是否生效
【用例描述】暂无用例
【自测情况】1. 测试过程：demo-application挂载demo-plugin进行测试；比较DemoCheckEnableDeclarer#isEnable()分别和true和false时，拦截点是否被增强。 2. 测试结果：true拦截点生效，false拦截点失效
【影响范围】插件开发过程中可以按自身场景来实现PluginDeclarer#isEnable()方法，可以减少某些场景无需增强的拦截点以提高框架的整体性能。
=> 【feature】支持插件自身决定是否要进行拦截点增强

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/common/CommonConstant.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadPropertiesStrategy.java
【修改内容】支持类spring方式配置.properties配置文件中的Map/List/Set
(1)支持如下方式配置Map
xxx.mapName.key1=value1
xxx.mapName.key2=value2
或
xxx.mapName=key1:value1,key2:value2
(2)支持如下方式配置List或者Set
xxx.xxx.listName[0]=elem1
xxx.xxx.listName[1]=elem2
或
xxx.xxx.listName=elem1,elem2
【用例描述】暂无用例
【自测情况】1. 测试场景：config.properties 按两种方式配置Map/List/Set；启动sermant-agent测试是否正确获取数据。2. 测试结果：各种方式sermant-agent均能正确获取配置文件。
【影响范围】.properties文件支持新的Map/List/Set配置方式
=> 【feature】优化.properties配置文件Map/List/Set数据格式配置

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadYamlStrategy.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java, sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/config/DemoConfig.java
【修改内容】优化properties和yaml配置文件数据格式支持以及环境变量读取
(1)通过在属性appName上添加@ConfigFieldKey("app-name")注解(举例)，可以在properties或yaml用中划线替换驼峰形式的键值(兼容驼峰形式)。
(2)config.yaml中xxx.xxx.appName将会直接以xxx.xxx.appName和解析为xxx.xxx.app.Name再通过KeyFormatter读取环境变量
(3)config.yaml中xxx.xxx.app-name将会被解析为xxx.xxx.app.Name再通过KeyFormatter读取环境变量
【用例描述】暂无用例
【自测情况】UT测试通过 
【影响范围】config.properties、config.yaml配置
=> 【feature】优化properties和config.yaml配置文件驼峰和中划线支持以及相应环境变量读取

sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/config/RegistrationProperties.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/AbstractBaseConfigDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/AbstractDoubleRegistryDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DiscoveryClientConfigurationDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DiscoveryClientDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/DynamicServerListLoadbalancerDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/cloud3/x/ZookeeperInstanceSupplierDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ConsulHealthDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ConsulWatchConDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/EurekaHealthDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/HealthIndicatorDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/NacosHealthDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ScheduleProcessorDeclared.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/declarers/health/ZookeeperHealthDeclarer.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DiscoveryClientInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/interceptors/DynamicServerListInterceptor.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/utils/HostUtils.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/client/ScClient.java
【issue号/问题单号/需求单号】#656
【修改内容】
- 适配Spring双注册的declarer开关
- 优化Spring双注册的去重逻辑
- 修正注册时的域名，保持与Spring Cloud保持一致
【用例描述】暂无用例
【自测情况】
测试场景：
（1）通过环境变量修改对应spring开关判断declarer是否正确的加载
（2）在双注册模式，通过注册两个相同的实例，测试相同的实例是否过滤掉，仅剩下一个。
【影响范围】spring注册
=> 【feature】适配declarer的开关，优化双注册去重逻辑

sermant-plugins/sermant-service-registry/spring-cloud-registry-service/src/main/java/com/huawei/registry/service/impl/RegisterCenterServiceImpl.java
【issue号/问题单号/需求单号】#662
【修改内容】修复webflux应用注册未就绪查询报错问题
【用例描述】暂无用例
【自测情况】本地自测通过
测试步骤：
（1）针对出错的webflux应用测试，携带agent启动
（2）通过断点以及日志方式判断是否再次报错
【影响范围】webflux应用注册
=> 【fix】修复注册在未就绪的情况下查询服务名报错的问题

sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/ContextClosedEventListenerInjectDefine.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/RequestInterceptorInjectDefine.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/grace/ContextClosedEventListener.java, sermant-plugins/sermant-service-registry/spring-cloud-registry-plugin/src/main/java/com/huawei/registry/inject/grace/SpringRequestInterceptor.java
【issue号/问题单号/需求单号】#664
【修改内容】修复基于配置中心下发优雅上下线开关存在类找不到的问题
【用例描述】暂无用例
【自测情况】本地自测通过
测试场景：
（1）设置应用环境变量关闭优雅上下线功能
（2）在配置中心配置开启优雅上下线功能
（3）测试应用调用，观察是否还存在类找不到的问题
【影响范围】spring优雅上下线
=> 【fix】修复基于配置中心下发优雅上下线开关存在类找不到的问题

sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadPropertiesStrategy.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/strategy/LoadYamlStrategy.java, sermant-agentcore/sermant-agentcore-core/src/main/java/com/huaweicloud/sermant/core/config/utils/ConfigValueUtil.java
【修改内容】修复properties和yaml配置文件缺省key时环境变量配置值不生效的问题
（1）properties配置文件
PluginConfig实现类对应的properties配置文件中，基本数据类型/数组/map/list/set缺省key时，支持从启动参数、环境变量、系统变量中依次获取配置值。（环境变量：map需配置为XXX_MAP_NAME=key1:value1,key2:value2格式；数组/list/set需配置为XXX_XXX_LIST_NAME=elem1,elem2。否则环境变量读取后解析失败）
（2）yaml配置文件
PluginConfig实现类对应的yaml配置文件中，支持基本数据类型/数组/map/list/set(不支持包含复杂对象)缺省key时从启动参数、环境变量、系统变量中依次获取配置值。（环境变量：map需配置为yaml字符串格式XXX_MAP_NAME={key1: value1, key2: value2}，数组/list/set需配置为yaml字符串格式XXX_XXX_LIST_NAME=[elem1,elem2]。否则环境变量读取后解析失败）
【用例描述】暂无用例
【自测情况】UT测试通过
【影响范围】config.properties、config.yaml配置
=> 【fix】修复properties和yaml配置文件缺省key时环境变量配置值不生效的问题

.github/workflows/intergration_spring_test.yml, sermant-integration-tests/scripts/downloadCse.sh, sermant-integration-tests/scripts/startCse.sh, sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/declarers/MutableSourceDeclarer.java, sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/interceptors/DynamicConfigSwitchSupport.java, sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/interceptors/MutableSourceInterceptor.java, sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/interceptors/ZookeeperLocatorInterceptor.java, sermant-plugins/sermant-dynamic-config/dynamic-config-plugin/src/main/java/com/huawei/dynamic/config/source/OriginConfigCenterDisableListener.java
【issue号/问题单号/需求单号】#670
【修改内容】
- 修复动态配置插件偶尔出现自动化测试失败的问题，主要基于spring环境变量优先级进行调整，当动态关闭配置中心时，动态提升sermant自身配置源优先级
- 自动化测试优化，maven依赖缓存，使用共享cse
【用例描述】暂无用例
【自测情况】本地测试通过；基于自动化测试action，多次测试暂未发现问题
【影响范围】动态配置能力
=> 【fix】基于动态方式提升动态配置优先级，确保动态关闭场景新的配置中心配置生效

sermant-plugins/sermant-flowcontrol/flowcontrol-service/src/main/java/com/huawei/fowcontrol/res4j/handler/CircuitBreakerHandler.java
【issue号/问题单号/需求单号】#682
【修改内容】修复熔断时间读取问题
【用例描述】暂无
【自测情况】本地自测通过；基于服务器打包测试通过
【影响范围】流控治理-熔断
=> 【fix】修复熔断时间窗口时间单位问题

sermant-plugins/sermant-router/dubbo-router-service/src/main/java/com/huaweicloud/sermant/router/dubbo/strategy/instance/MismatchInstanceStrategy.java, sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/RouterConfiguration.java, sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/label/entity/ValueMatchDeserializer.java, sermant-plugins/sermant-router/router-config-common/src/main/java/com/huaweicloud/sermant/router/config/utils/RuleUtils.java
【issue号/问题单号/需求单号】 #684 
【修改内容】1.去掉解析路由策略的警告日志；2.修复attachments被覆盖的问题
【用例描述】暂无用例
【自测情况】
- 本地测试，配置路由规则时，配置不存在的值匹配策略，不再打印日志;
- 同时配置headers和attachments，attachments不会被覆盖
【影响范围】路由插件
=> 【fix】修复路由插件的bug

sermant-agentcore/sermant-agentcore-config/config/all/config.properties, sermant-agentcore/sermant-agentcore-config/config/config.properties, sermant-agentcore/sermant-agentcore-config/config/example/config.properties, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/config/FlowControlConfig.java, sermant-plugins/sermant-flowcontrol/flowcontrol-common/src/main/java/com/huawei/flowcontrol/common/enums/MetricSendWay.java
【issue号/问题单号/需求单号】 #689 
【修改内容】修复netty一直重连的bug 
【用例描述】暂无用例
【自测情况】启动demo应用，netty不再重连
【影响范围】agent core
=> 【fix】修复netty一直重连的bug 

sermant-example/demo-plugin/pom.xml, sermant-example/demo-plugin/src/main/java/com/huawei/example/demo/service/DemoSimpleService.java, sermant-example/demo-plugin/src/test/java/com/huawei/example/demo/interceptor/DemoInterceptorTest.java, sermant-example/demo-plugin/src/test/java/com/huawei/example/demo/service/DemoServiceTest.java
【issue号/问题单号/需求单号】#674
【修改内容】新增interceptor(插件拦截器)和service(插件服务，包含获取插件配置)单元测试模版。
各位在开发新插件时，需按照模板要求编写interceptor和service的单元测试，以保证插件基本能力和代码质量。
【用例描述】无需用例
【自测情况】UT测试通过
【影响范围】插件拦截器和插件服务相关UT
=> 【doc】插件interceptor和service单元测试模版
